microsoft/vscode-go

src/goFormat.ts

The information message provided was explicitly for 'goreturns', should reflect the configured formatCommand.  Also not sure if providing go get information is particularly useful here, since extension already allows for the installation of tools.

Update formatCommand error messaging

---

src/goCheck.ts
src/goPath.ts

I request to merge to correction tested for windows plugin usage. 
First bin path extraction from gopath should be consistent, and in windows it is required to test file with it's extension
Build tool will emit errors like: myfile.go:4:6: expected 'STRING', found newline
where 4 is the line number and not 6

Fix gopath bin location search and error in error line parsing in windows

---

README.md

The commit in this merge request aligns the README file with the [actual list of required tools](https://github.com/Microsoft/vscode-go/blob/ffe08258aeeca36668302c00e2b5cd0127d2df98/src/goInstallTools.ts#L42).

Add go-outline under Tools in README file

---

src/goRename.ts

Also don't return a null thenable if gorename isn't found.
https://github.com/Microsoft/vscode-go/issues/71

gorename: fix incorrect path logic.

---

package.json
src/goFormat.ts
src/goMain.ts

Adds a new "go.formatOnSave" which is off by default.  Turning this feature on will cause 'save' to format using the currently selected `go.formatTool` and then error check.
Note that using this feature along with `AutoSave` will result in some fairly aggressive reformatting of your code in the middle of typing.  It is suggested that you use one or the other but not both concurrently.
Fixes #14.

Format on save

---

.vscode/settings.json

Help enforce formatting conventions by disabling spaces-as-tabs.
If hard tabs aren't actually the convention, please let me know. :grin:

Use tabs instead of spaces by default in workspace settings

---

package.json
src/goCheck.ts
src/goMain.ts
src/goPath.ts
src/goTest.ts

Introduce a 'go.test.cursor' command which executes the unit test at
the primary cursor location. Output is placed in the 'Go' channel.
Refactor references to the Go runtime path.
Closes #88

Introduce command to run test at cursor

---

package.json
src/goMain.ts
src/goTest.ts

Introduce 'go.test.package' and 'go.test.file' commands.
Closes #89.

Introduce more unit test commands

---

README.md
src/goImport.ts
src/goInstallTools.ts

This solves the slow "Add import" as discussed at #159 by incorporating gopkgs suggested and provided by tpng.

incorporating gopkgs for quick lookup of available packages

---

README.md
package.json
src/goSuggest.ts

Func parameter completion or hinting is a bit old but significant issue mentioned at #9, #128 and #135.
This change solves this issue by inserting a complete snippet of the function or method selected from the suggestions.
An example:
At last argument, tab would set the cursor after the closing bracket.
This takes the same approach as Atom's go-plus and GoSublime.
Personally, I like this approach better than a pop-up that hides my code as I'm filling parameters.

func param completion

---

src/goSuggest.ts

Some functions have parameters with interface{} type and if those brackets aren't escaped, the function snippet is incorrect.
This change escapes those brackets.

escape brackets in func completion snippet

---

README.md

The location of documentation on Delve has changed recently.

docs: Update installation documentation for Delve

---

src/goDeclaration.ts
src/goExtraInfo.ts

GoHoverProvider was throwing a TypeError trying to read a property
from null definition locations. It may be more appropriate to try
and prevent the hover provider from entering its handler function if
definitionLocation finds no match, but rejecting the Promise didn't
see to do the trick. This patch makes the HoverProvider call a no-op
when no definition is found.
Fixes https://github.com/Microsoft/vscode-go/issues/255

Make HoverProvider tolerate missing locations

---

src/goInstallTools.ts

fixes #237
When I launch `code` from my shell, it does not respect GOPATH environment variable of **current shell**, which sets GOPATH to:
```sh
export GOPATH="${PWD}/deps:${PWD}"
```
So, I set `go.gopath` in `.vscode/settings.json`:
```json
{
"go.gopath": "deps:."
}
```
Then, Go To Definition tries to open `/deps/src/{somefile}` and fails.
With this pull request, I can set `go.gopath` as:
```json
{
"go.gopath": "${workspaceRoot}/deps:${workspaceRoot}"
}
```
And,  Go To Definition functions as expected.

Expands ${workspaceRoot} in go.gopath configuration

---

package.json
src/debugAdapter/goDebug.ts

I have added support for remote debugging.  I did this by adding remotePath, port, and host properties to configuration.  Also, mode property must be set to debug_remote.  Could not find graceful way to shut down remote dlv process, so I just issue a halt command and the developer must Ctrl-C on the remote dlv process.  Hopefully, you can merge this request in.  Nice to be able to debug in vscode!  Thanks.

Added support for remote debugging.

---

package.json
src/goSuggest.ts

Introduce a setting to allow disabling gocode's experimental autobuild
support. Enabling it can cause performance issues in large codebases,
and users should have the capability to assume full control over when
go build and install is invoked.

Introduce gocode autobuild setting

---

README.md
src/goInstallTools.ts
src/goReferences.ts

The oracle tool has been forked and replaced with the guru tool.
Switch vscode-go to use guru instead of oracle to take advantage
of the revived progress on the tool.
Fixes #284

Replace oracle with guru

---

package.json
src/debugAdapter/goDebug.ts

This is a small patch that makes it possible to toggle delve's debugging output.
I've found it to introduce a lot of pointless noise, distracting from *meaningful* stderr output.

Disable the delve --log option by default.

---

.travis.yml
README.md
package.json
src/goExtractMethod.ts
src/goFormat.ts
src/goInstallTools.ts
src/goMain.ts
src/util.ts
test/fixtures/expectedAfterExtractMethod.go
test/go.test.ts

Related to a feature ask in #275 
This commit adds a command to the command palette that can be used to extract a method out of selected code and replace the selected code with a call to the extracted method using godoctor. Read more about godoctor at http://gorefactor.org/

Add command to extract method out of selected code

---

src/goCover.ts

This fixes an issue on OSX where the temporary file used by the go code cover integration doesn't exist. This in turn breaks other tasks run on save.

Make sure tmp file for go code cover exists

---

src/goInstallTools.ts
src/goReferences.ts
src/goSuggest.ts

This commit causes goInstallTools to log very differently than present.
Presently, goInstallTools just writes the output of stdout and stderr to the Go outputChannel.
This commit proposes logging _much_ less in the case of success, and only logging the cause of errors.
Let me know what you think @lukehoban.
(A total success)
```
Installing 9 missing tools
gorename
gopkgs
gocode
goreturns
godef
golint
go-outline
go-symbols
guru
Installing gopkgs SUCCEEDED
Installing go-outline SUCCEEDED
Installing go-symbols SUCCEEDED
Installing godef SUCCEEDED
Installing gorename SUCCEEDED
Installing golint SUCCEEDED
Installing goreturns SUCCEEDED
Installing gocode SUCCEEDED
Installing guru SUCCEEDED
All tools successfully installed. You're ready to Go :).
```
(A failure)
```
Installing 9 missing tools …
```

Fixes #310 - install Missing Analysis Tool. Better feedback would be nice

---

.travis.yml
package.json
src/goCheck.ts
test/go.test.ts

ran into [this](https://github.com/alecthomas/gometalinter/issues/119)
not sure what should I do

Add go-metalinter support

---

package.json
src/goInstallTools.ts
src/goMain.ts

Once the dependencies have been found once, users cannot trigger a reinstall or update of the go pkgs used by vscode. This PR provides a command to installer or update all tools at once.

provide a command to install/update the go dependencies

---

README.md

I didn't realize that a lot of the great go tools were already supported thanks to gometalinter. I was particularly interested in running `errcheck` on save (it verifies that all errors are being handled).  The linter change wasn't really documented and I didn't even realize that by switching linter I would get access to all these amazing tools.
This PR is a simple README update that explains what is a linter, how to change it and how to setup/customize gometalinter.
cc @egamma

readme: more info about the linter features

---

src/goDeclaration.ts
src/goExtraInfo.ts
test/go.test.ts

This patch enables godoc provided documentation on function hover.
I have no idea why this was implemented but not enabled. Was there any reason?
This may not be desirable since it runs two programs on hover, and can be improved in a followup PR to use gogetdoc. That said, these processes are called everytime the developer writes a function call, which happens (at least for me) way less often than hovering a method.
It's also better than the documentation on parenthesis open, since it is not truncated.
Note that this does not enable the godoc in resolveCompletionItem, that may come in another PR :)
Fixes #87

Extra info now checks doc

---

package.json

Related to [delve debugger non-functional in VSCode 1.3.1](https://github.com/Microsoft/vscode-go/issues/410)
`showLog` was added as a new option in 0.6.40.  When set to false (the default), the debugger appears not to work.  Adding `"showLog": true` to the initialConfigurations allows the debugger to work with the auto generated launch.json.

Add showLog to initialConfigurations

---

src/goPath.ts

When the bin path for tools are not found, the tool name is cached as bin path. Therefore, even after the tools get installed, the right path to the tools are never used.

Do not cache bin path for tools when they are not found. Fixes #456

---

README.md

Quick change to the README to include the go format options, as found in:
https://github.com/Microsoft/vscode-go/blob/dca9bef794ba1a40f42a1dff63ab5fe9658e4652/package.json#L270

Added go format flags to README

---

src/goFormat.ts

On windows, when the format tool doesn't exist, vscode-go will show ".exe" at the end of the command, breaking the installation.
This patch fixes it.

Fix the executable name so ".exe" doesn't end up in the install warning

---

test/go.test.ts

Fixes #479.  A little bit of a hack - but really something that should be solved in VSCode itself.

Don't use vscode config directly in tests

---

src/goTest.ts

Send Go test output to a dedicated output channel. Re-using the "Go"
channel from the status component causes a lot of confusing
interspersed unrelated output, and the test command often clears the
"Go" channel, obliterating things users might want to see.

Send test output to a distinct output channel

---

package.json

Improve the test command titles by removing the parentheticals. This
fixes autocompletion for these commands through the command palette
which would not previously recognize, for example, "testcur" as the
"Go: Test (cursor)" command.

Improve test command titles for autocompletion

---

package.json
src/goMain.ts
src/goTest.ts

Add a `go.test.previous` command which runs the last test which was
executed.

Add a command to execute the previous test

---

src/goImport.ts
test/go.test.ts

Fixes #494 
In this PR, while returning list of packages that can be imported, `go-outline` tool is run on the file to get list of  already imported packages so that the list returned by the `Go: Add Import` command can be filtered
Since we only need to parse the file for imports, parsing the whole file is unnecessary. 
https://github.com/lukehoban/go-outline/pull/4 adds the option to parse for imports only to the go-outline tool. Once that PR is merged, we can make use of the "parse imports only" feature

Do not allow import for already imported pkgs

---

.travis.yml
README.md
package.json
src/goGenerateTests.ts
src/goInstallTools.ts
src/goMain.ts
test/go.test.ts

Add support for gotests "https://github.com/cweill/gotests"
Implements three new commands that use gotests:
- go.test.generate.package: generates all unit-test squeletons for
the current package.
- go.test.generate.file: generates all unit-test squeletons for
the current file.
- go.test.generate.function: generates unit-test squeleton for the
selected function in the current file.

Add support for gotests "https://github.com/cweill/gotests"

---

package.json
src/goImport.ts
src/goSuggest.ts
test/go.test.ts

This PR adds 2 features
1. **Auto-complete for package names that are not imported**. Example:
Assume you haven't imported `fmt`, type `f`, the auto-complete will give `fmt` as an option. Choose this option, the word will get completed and an import to `fmt` will be added to your go file
2. **Auto-complete for methods from packages that are not yet imported**. Example:
Assume you haven't imported `math`, type `math.`, the auto-complete will give all methods from `math` package as options. Choose any, the word gets completed and an import to `math` will be added to your go file
These features depend on updates to the CompletionItem API in VS Code 1.5
Fixes #407 and #437

Add completion items for unimported packages

---

src/goImport.ts
src/goInstallTools.ts
test/go.test.ts

PR to fix #316 
This PR uses the prefix from the full path of vendor packages, appends that to $GOPATH to get the path to the vendor folder, tries to match it with current file path to see if both belong to the same project. If yes, then the relative path of the vendor replaces the full path.
Another way to find relative paths for vendor packages is by using the govendor tool:
`govendor list -no-status +v` gives the list of vendor packages (with relative path) for current go project.
But using this adds a 1 second delay between executing the command `Go: Add Import` and showing the results in Windows. In Mac, the difference is much less.
The implementation using govendor is here: https://github.com/ramya-rao-a/vscode-go/blob/vendor-imports-using-govendor/src/goImport.ts
Thoughts on both …

Fixes #316 Replace full path for vendor packages with relative path

---

package.json
src/goFormat.ts

For some users using `-d` while formatting is not giving any results.
This PR adds a setting that can be used to disable the use of `-d` while formatting to unblock such users, until we find the problem with the formatting tool

Add setting to control use of -d flag by the formatting tool

---

src/debugAdapter/goDebug.ts
src/util.ts

Fix #552.
This is copied from node-debug/node-debug2. It doesn't check whether a port is already in use, but... there are lots of ports out there. Without this, debugging two Go processes with a 'composite' launch config won't work out of the box without specifying ports manually.

Select a random port to debug on

---

src/goImport.ts
src/goInstallTools.ts
src/goOutline.ts
test/go.test.ts

We use `go-outline` tool to get list of imported packages in the current file. `go-outline` internally parses the file to return all symbols. But since we need only imports, the whole file need not be parsed. https://github.com/lukehoban/go-outline/pull/4 added the option to parse only the initial part of the file that contains the imports.
This PR uses this option.

Use -imports-only option from go-outline

---

src/goImport.ts
src/goInstallTools.ts
src/util.ts
test/go.test.ts

Fixes #545 
- Moved `getGoVersion`, `SemVersion` and `isVendorSupported` from `goInstallTools.ts` to `util.ts`
- check for GO15VENDOREXPERIMENT env var is added for Go 1.6 because
> Go 1.5 introduced experimental support for vendoring, enabled by setting the GO15VENDOREXPERIMENT environment variable to 1. Go 1.6 keeps the vendoring support, no longer considered experimental, and enables it by default. It can be disabled explicitly by setting the GO15VENDOREXPERIMENT environment variable to 0. Go 1.7 will remove support for the environment variable.
- If no release tag is found and GO15VENDOREXPERIMENT is explicitly set to 0, `isVendorSupported` will return false. 
- If no release tag is found and GO15VENDOREXPERIMENT is not explicitly set to 0, `isVendorSupported` will return true. 
- If …

Fix for when Go is used from source without release tag

---

src/goTest.ts

Implementing the same that was attempted in #388 which at the time failed because the Go extension was using a very old vscode.d.ts

Preserve focus while running tests

---

src/goGenerateTests.ts

Dont generate unit tests for non Go files

---

package.json
src/goFormat.ts
src/goMain.ts

Support editor.formatOnSave

---

src/goSuggest.ts

Fixes #573 by
- Ignore escaped double quotes while counting double quotes in current line to determine if cursor is inside a string
- If cursor is right outside a string, return no suggestions
- Do not suggest unimproved pkg related suggestions, if cursor is inside string
**A little history:**
By default, vscode does not trigger auto-complete for special symbols like double quotes unless the extension implementing the autocomplete specifically says so.
The Go extension does ask for auto-complete for double quotes to support the scenario where you import packages like `import ma` should give options for packages starting with "ma"

Fixes #573 Update logic that determines in string position

---

src/goInstallTools.ts
src/goMain.ts
src/util.ts

When no GOPATH is set, the status bar has a note that "GOPATH not set"
This is not very visible and some users might have disabled the status bar too

Fixes #582 Prompt to set GOPATH

---

src/goInstallTools.ts

We have been using Go from GOROOT (falling back to PATH if not found) everywhere while running the `go` command except while installing tools.
This PR will fix that
Fixes #592

Fixes #592 Use go from GOROOT while installing tools

---

package.json
src/goGenerateTests.ts
src/goMain.ts

Implementing Feature Requests from #432 and #566

Open Test Files

---

src/goSuggest.ts

Ever since we introduced importable packages as suggestions in the auto-complete, people have found it annoying that these package suggestions are interspersed among variables/function names etc.
Excerpt from Gitter:
> After last plugin update in autocompletion list I got list of all available packages, it's pretty cool but little annoying because variables with corresponding names appears in the end of a list. It would be nice to sort this list and show variables on top
This PR is to group all the package suggestions and make them appear AFTER the usual/normal suggestions from `gocode`.

pkg suggestions to appear after gocode suggestions

---

snippets/go.json

Useful snippets to me that is.

add a few useful snippets

---

src/goImport.ts
test/go.test.ts

Fixes #598 
The functions `disallowVendor` and `disallowVendorVisibility` in https://golang.org/src/cmd/go/pkg.go make it clear that importing a vendor package from another project is not allowed in Go.

Dont allow import on vendored pkg from another project

---

src/goSuggest.ts
test/go.test.ts

Fixes #598 
Say there is a variable by the name `math` in a Go file. Completion items after typing `ma` will include results for both the variable `math` and the package `math` that can be imported. The latter is not valid.
This PR excludes importable packages with same name as any other identifier in the Go file

Remove pkgs from completion if identifier with same name exists

---

src/goSuggest.ts

when `"go.useCodeSnippetsOnFunctionSuggest": true`，if a function auto completed brackets，there are a black space will insert after it. This's pull request will fix it.

remove black space after auto completed brackets

---

src/goDeclaration.ts

Don't return a failure in definitionLocation() when getGoVersion()
returns a null version. Instead, assume it's newer than Go 1.5.

Fix "Go to Definition" when running Go HEAD

---

snippets/go.json

Analogical to existing `tf` snippet.

Add benchmark function snippet

---

src/util.ts

Fixed wrong workspace when one gopath is the substring of another in “canonicalizeGOPATHPrefix” of “util.ts”.

Fixed wrong workspace when one gopath is the substring of another.

---

src/goImport.ts

Support cases when the vendor packages are under `$GOPATH/src/vendor`. Fixes #647

Support vendor pkgs from root of GOPATH/src

---

src/goSuggest.ts

Support versioned packages from [gopkg.in](http://labix.org/gopkg.in) Fixes #647

Strip version from autocompleted pkgs from gopkg.in

---

src/goInstallTools.ts

Make `go get` honor http.proxy setting so that user can not only provide their proxy settings via environment variables

Add support for reading http.proxy setting

---

src/goCover.ts

getCodeCoverage gets triggered when vscode.window.onDidChangeActiveTextEditor fires. onDidChangeActiveTextEditor also fires when the active editor changes to undefined.

fix coverage display when editor changes to undefined

---

src/goDeclaration.ts
src/goSuggest.ts
src/util.ts
test/fixtures/gogetdocTestData/test.go
test/go.test.ts

The Go extension spawns a new process to get definition information each time the hover provider is triggered. This sometimes results in massive number of processes to spin up and cause perf issues.
When we know beforehand that the text under the cursor is not an identifier, then we can skip creating new processes to get definition information. 
In this PR, we do this for the below cases:
- Not a word
- Is a keyword
- Is a number
- Is part of a string literal
- Is part of a single line comment

Do not get definition info if not identifier

---

src/debugAdapter/goDebug.ts

Honor the 'cwd' launch configuration argument

---

README.md
src/goInstallTools.ts
src/goPath.ts

This is a prototype for issue #5.
The approach used in this prototype allows users to install the Go tools in a separate GOPATH by setting a VSCODE_GOTOOLS env variable to the directory of where they want to install the tools. 
1. What do you think of the overall approach?
2. Is VSCODE_GOTOOLS a good name for the env variable?

Allow Go tools to be installed in a separate GOPATH

---

src/goInstallTools.ts

Relatively meaningless PR to fix an extremely minor annoyance

Use proper plurality in installation console output

---

src/goCover.ts

- The previous condition did not catch any errors when `go test` for retrieving coverage failed.
- Use an output channel to show the error message. showInformationMessage is only good for single lines.
Fixes #350

Improve error handling of test coverage

---

src/goCheck.ts
src/util.ts
test/go.test.ts

This PR addresses the compilation performance optimization discussed in #673.
Installing the built packages improves following compilations since packages are only rebuilt if they changed.
If the current package is a main package, the installation is skipped to avoid installing executable binaries.
I had to tweak a util method that was scanning text files to find the package and the imports. Unfortunately this util wasn't tracking the name of the package. I needed the package name to check if the `-i` flag should be used or not.

if buildOnSave is on: build using -i

---

src/goCheck.ts
src/goInstallTools.ts

- Install `gometalinter` and run `gometalinter --install` to completely set up the tool if the user has chosen it as their linttool
- If there are errors while running `go vet` or while linting, show them in the output channel
- If there are build errors that do not match expected format of file name, line numbers etc., show them in output channel instead of ignoring them
cc @roblourens

Build and linting improvements

---

package.json
src/debugAdapter/goDebug.ts
src/goCheck.ts
src/goCover.ts
src/goDeclaration.ts
src/goFormat.ts
src/goGenerateTests.ts
src/goImport.ts
src/goInstallTools.ts
src/goOutline.ts
src/goPath.ts
src/goReferences.ts
src/goRename.ts
src/goSuggest.ts
src/goSymbol.ts
src/util.ts
test/go.test.ts

See #5 for the discussion on the need for a separate location to install Go tools instead of the user's GOPATH.
See #351 for the implementation using env vars and further talk of how a VS Code setting is better instead of env var
This PR is to use VS Code setting where user can provide a location for installing the Go tools.
`gometalinter` is an exception to this rule and will get installed in the user's GOPATH always.
This is because `gometalinter` expects all the linters it uses to be in the user's GOPATH.
Users need to install `dlv` manually as always and is out of this disucssion
cc @roblourens

Use settings for separate location for installing Go tools

---

src/goCheck.ts

Map unexpected errors to first line

---

src/diffUtils.ts
src/goCodeAction.ts
src/goDeclaration.ts
src/goExtraInfo.ts
src/goFormat.ts
src/goInstallTools.ts
src/goMain.ts
src/goSignature.ts
test/go.test.ts

Today, when you change your choice of formatting or docs tool, you need to reload VS Code for that to change to take effect.
With this PR, no more reload needed in such cases.

No more reload when choice of tool is changed

---

package.json
src/goMain.ts
src/goTest.ts

(Updated on 21/1/2017)
Fixes #401 and #683
Added a new setting `go.testFlags`
- If null, then all the test commands will continue to use the `go.buildFlags` and '-v' while running `go test` as always.
- Else, the provided flags will be used by the test commands  instead of `go.buildFlags`  while running `go test`
The usage of `go.testTimeout` and `go.buildTags` will continue to remain as is.
Users can also customize the flags and have keyboard shortcuts for the same.
```json
{
"key": "ctrl+shift+t",
"command": "go.test.file",
"args": {
"flags": ["-short"]
},
"when": "editorTextFocus"
}
```

Enable testflags via settings and keyboard bindings

---

src/goMain.ts
src/goPath.ts

When `go.toolsGopath` changes, we need to clear the cache (for tools path), so that the extensions starts looking at the new `go.toolsGopath` without needing a VS Code window reload

Clear cache for tools when toolspath changes

---

src/goInstallTools.ts
src/util.ts

The same was done for go.gopath in https://github.com/Microsoft/vscode-go/commit/f83579f568055f8528234f56d32238f308f47ddb
Fixes #761

Expands ${workspaceRoot} in go.toolsGopath configuration

---

README.md
package.json
src/goInstallTools.ts

I would like to propose this implementation for the feature request raised in #757

added go.inferGopath. Similar to GoSublime's use_gs_gopath

---

src/debugAdapter/goDebug.ts

also returning '\\' as a separator on Windows paths with mixed separators.
PR as requested in #689.

Removing common parts from program and remotePath

---

src/debugAdapter/goDebug.ts

When delve fails, stop the debug sessions

---

package.json
src/goOutline.ts

The Go To Symbols in File feature currently lists all the import statements as symbols as well.
This becomes noisy for a file with a lot of imports and hinders symbol search as well.
See https://github.com/Microsoft/vscode-go/issues/680#issuecomment-267515076
This PR ignores the import statements in the Go to Symbol File feature.
Will keep a setting to include them. 
Based on the telemetry, we can see how many users turn it back on to include imports, and then take the call to remove the setting if needed.

Ignore import statements in Go to Symbol in File feature

---

src/util.ts

When using multibyte characters like 🚨 in comments, actions like hover and go-to-def were using wrong offsets after that character.

fix offsets for files with multibyte characters

---

src/debugAdapter/goDebug.ts

The program attribute should point to a valid file or directory for selected mode. This patch improves error messages shown when program attribute is invalid. Fixes #782.

Verify the program attribute passed to debugAdapter

---

src/goOutline.ts

because they are used in an exported function.
These paths caused me problems when I was trying to pursue method 1 in https://github.com/Microsoft/vscode/issues/20623
```
[17:13:16] Starting 'watch-client'...
[17:14:20] Error: /Users/nick/code/vscode/extensions/vscode-go/src/goOutline.ts(37,42): Parameter 'options' of exported function has or is using private name 'GoOutlineOptions'.
[17:14:20] Error: /Users/nick/code/vscode/extensions/vscode-go/src/goOutline.ts(37,69): Return type of exported function has or is using private name 'GoOutlineDeclaration'.
```

export GoOutlineRange, GoOutlineDeclaration, GoOutlineOptions

---

src/diffUtils.ts
src/goFormat.ts
src/goRename.ts

These paths caused me problems when I was trying to pursue method 1 in https://github.com/Microsoft/vscode/issues/20623
When running `./scripts/code.sh` in vscode I saw:
```
[85253:0214/175725:INFO:CONSOLE(84)] "Activating extension `lukehoban.vscode-go` failed: Cannot find module '../src/diffUtils'.", source: file:////Users/nick/code/vscode/out/vs/workbench/services/message/browser/messageService.js (84)
```
Seems like these paths are otherwise equivalent so I hope this doesn't cause a problem elsewhere.

clean up import paths

---

README.md
package.json
src/goCheck.ts
src/goCover.ts
src/goMain.ts
src/goTest.ts

This is a very straightforward implementation of the testOnSave feature (#581).
I suppose it would be much better to compile sources only one time if buildOnSave, testOnSave, and coverOnSave are on: `go test -c` includes everything from `go build`, cover is obtained from tests.
Also it would be nice to have some sort of progress bar, but I have no idea where it should be placed.

Add go.testOnSave option

---

src/goCheck.ts
src/goMain.ts

Show test status until a file is changed

---

src/goSuggest.ts

Add keywords to completion list

---

src/diffUtils.ts

Fixes #665 
Root cause: https://github.com/kpdecker/jsdiff/issues/171

Clean up filename after parsing diff output

---

src/goInstallTools.ts

Read GOPATH, GOROOT from go env

---

src/debugAdapter/goDebug.ts

Supported only when `mode = debug` and `program` points to a file

Fixes #299 Run without debug

---

CHANGELOG.md
README.md
package.json
src/goInstallTools.ts
src/goMain.ts
src/goModifytags.ts

Use gomodifytags to add/remove tags from struct fields

---

src/goTest.ts

Fixes #241
The output from `go test -v` in case of test failures look like this:
This PR is to expand the filename to its absolute path, so that it is clickable and acts as a link to the test file

Fixes #241 Use absolute path in output pane to support links

---

README.md
package.json

As a test run, I am planning to ship this in the coming update
People who feel this would clutter their menu and are comfortable using the command pallet instead, can change the settings to disable these entries
Sub menus are not supported yet, if they were then we could group these more appropriately.
This can act as a feature discovery tool, which users can prune as per their needs.

Fixes #728 Add commands to context menu

---

.travis.yml
README.md
package.json
src/goInstallTools.ts
src/goSymbol.ts
test/go.test.ts

This uses https://github.com/acroca/go-symbols/ which is a fork of https://github.com/newhook/go-symbols. Didnt get a response to merge the former to the latter, therefore using the fork.
Fixes #700

Option to Ignore folders while workspace symbol search

---

README.md
package.json
src/goInstallTools.ts
src/goLiveErrors.ts
src/goMain.ts

This PR adds an optional (disabled by default) live error reporting system.
Closes #883
I've used many editors in which a live as-you-type feedback system was available. I've found that it helps me catch errors as they happen and fix them immediately. This constant feedback allows me to code more quickly, as I am still in the context of an error when I see it, rather than having to come back to it after the build has failed.
To implement this feature, I have taken advantage of my custom fork of [gotype](https://godoc.org/golang.org/x/tools/cmd/gotype), called [gotype-live](https://github.com/tylerb/gotype-live).
My fork enables the processing of an in-memory version of a file by accepting the contents via stdin. This allows us to get errors back from `gotype` as we code, rather than …

Add live error feedback as you type

---

test/go.test.ts

Travis tests have been failing consistently due to gometalinter running slow linters.
This PR is to restrict the #  of linters being run by gometalinter

dont run slow linters

---

src/goMain.ts

This patch modifies `go.debug.startSession` command to add  environment variable 'GOPATH' to launch configuration JSON object. A proper `GOPATH` is searched using `getBinPath`, which utilizes VSCode settings.
This allows more versatile configuration and provides better out-of-box experience.

set GOPATH for debug adaptor automatically

---

src/goLiveErrors.ts

There exists an issue with the live error system in that `gotype-live` will report errors for all files in the package, but the document change event is only for a single file. As a result, all the errors, for all the files, were being displayed as errors in the current file. This PR fixes that issue.
It may be worthwhile to investigate the possibility of displaying those errors for the correct file.

Fix gotype-live errors showing in wrong file

---

.travis.yml
src/goGenerateTests.ts
src/goInstallTools.ts
src/goModifytags.ts
src/goOutline.ts
src/goTest.ts
src/util.ts
test/go.test.ts

Since https://github.com/lukehoban/go-outline/pull/7 is not being merged in time, we will use a fork of `go-outline`

Fixes #922 Pass file contents to go-outline

---

.gitignore
src/debugAdapter/goDebug.ts

Works fine for me after I moved this :)
Fixes   #934

move env consolidation after loading envFile

---

README.md
package.json
src/goCodelens.ts
src/goMain.ts
src/goReferences.ts

This PR adds support for reference codelenses as discussed in https://github.com/Microsoft/vscode-go/issues/726
There are still a few issues:

Add references codelens support

---

src/goCodelens.ts

Using `resolveCodeLens` reduces the initial load when opening files in bigger projects a lot. But references are only counted when a function is visible which means it can take sometime until the references are displayed

Use resolveCodeLens for better performance

---

src/goCodelens.ts
src/goMain.ts
src/goRunTestCodelens.ts
src/goTest.ts

Same feature as Test at Cursor, but in this case there is no need to select anything.
It's based on C# VSCode extension.
What you think about it?
I didn't provide any flag to disable it, because it's possible to do so with standard editor flag: `"editor.codeLens": false`.

RunTest with CodeLens

---

package.json
src/goCheck.ts

This will let users set env variables for `go build` (e.g. `CGO_CFLAGS`, `CGO_LDFLAGS` and `LD_LIBRARY_PATH`).

Set environment variables for go tools

---

src/goRunTestCodelens.ts

Command **"debug test"** from codelense did not populate env vars with those from workspace config. Usually this command runs in same environment as plain tests, so it is natural to expect **testEnvVars** from workspace config being used.
This pr fix behavior to expected.

Add testEnvVars from workspace config to debug environment

---

package.json
src/goImpl.ts
src/goInstallTools.ts
src/goMain.ts

A start of the goimpl implementation, pretty simple feature as it exists right now, just pop open the info box, take the information and then inject the stdout at the cursor position.
I see a few ways it could be improved, but figure it was better to just get the simple implementation done.
Idea for improvement
* Check if cursor is on a typedef, if so, allow input to only contain interface
* If cursor is not on a empty line, ensure to insert selection on first empty line below cursor

Goimpl implementation

---

package.json
src/debugAdapter/goDebug.ts
src/goPath.ts
src/goRunTestCodelens.ts
src/goTest.ts
src/util.ts

The main purpose of this pull request is to enable use of .env files when running/debugging tests through VSCode no matter what triggered it (CodeLens, Tasks, Command ...)
This pull request contains:
1) New `go.testEnvFile` configuration option with same intent as envFile from vscode debug settings;
2) Any test function ran by vscode-go will load env variables from: `process.env`, `go.toolsEnvVars`, `go.testEnvFile` and `go.testEnvVars`;
3) Debug CodeLens now loads `go.testEnvFile` and `go.testEnvVars`;
4) moved .env parser to a specific function for reusability purpose;
I didn't like this bit here `testEnvFile = testEnvFile.replace(/\${workspaceRoot}/g, vscode.workspace.rootPath);`, but didn't find any other way to do so.
Regards,
Guilherme

add support for testEnvFile

---

package.json
src/goCheck.ts

Changes the default behavior from running lint/vet/build for the package of the current active file to running it for the entire workspace.
Potential downside is not having a flag which allows the behavior to be changed between `current package` and `workspace` (as with #830). Something for the future.

Run on-save tools for entire workspace

---

src/goInstallTools.ts

Show full package import path for tools install result.

---

README.md
package.json
src/goInstallTools.ts

This PR adds support for @dominikh's all-in-one linter tool. Generally it's much quicker than `gometalinter` and uses fewer resources, as it shares work between all checks.

Add support for megacheck as the lintTool

---

src/goImport.ts
src/goMain.ts
src/goPackages.ts
src/goSuggest.ts
test/go.test.ts

Fixes #647
`gopkgs` only return the import paths of the packages that can be imported and not the package names.
Since the last part of the import path of a package need not necessarily be the package name, we cannot always decipher package name from the import path.
In this PR, we use `go list all` instead.
`go list all` is expensive. So should be used sparingly. In this case, it is run on extension activation.

Use go list all to get pkgname to use in completions 

---

src/goBrowsePackage.ts
src/goPackages.ts

1. In certain cases, `go list all` was throwing "buffer too large" so it needed to be streamed.
2. No need to highlight an import path to get `Browse Packages` to show the files of that import path.

Stream 'go list' cmd for large Browse Packages imports

---

src/goBrowsePackage.ts

tiny housekeeping : ) -- feel free to close if you'd like to include with another pr

Housekeeping: deconstruct activeTextEditor in goBrowsePackages

---

src/goPackages.ts
src/goTest.ts

This is to avoid test vendor directory when using vendor tools such as Glide

Exclude 'vendor' directory when test all workspace

---

src/goPackages.ts

If a user has a different GOPATH, the `env: {}` will only bring the standard library list of packages.

Go list cmd: include GOPATH when a custom one exists

---

snippets/go.json

`helloweb` generates small web app with an http endpoint
which returns a greeting and the current time.
This is can be used to quickly generate a minimal web app
for demo purposes.
The generated code looks like:
```go
package main
import (
"fmt"
"net/http"
"time"
)
func greet(w http.ResponseWriter, r *http.Request) {
fmt.Fprintf(w, "Hello World! %s", time.Now())
}
func main() {
http.HandleFunc("/", greet)
http.ListenAndServe(":8080", nil)
}
```

Add helloweb snippet

---

src/goTest.ts
src/util.ts

This supposed to solve issue #1120

Return the output immediately both for stdout and stderr

---

package.json
src/goImplementations.ts
src/goMain.ts

Add an ImplementationProvider based on the Go `guru` tool.
Based on @codmajik's work in https://github.com/codmajik/vscode-go/commit/3bf018bab0b86ccf16aeefb6286cab6a8f63e8aa.
Fixes https://github.com/Microsoft/vscode-go/issues/771.
TODO:

Guru ImplementationProvider

---

src/debugAdapter/goDebug.ts

The Delve **this.program** is compared against a **normalizedPath in the this.toDebuggerPath() function** and it needs to be noralized before this is done otherwise **it will end up returning the wrong path for the remote file**.  This can be seen when running a Windows 10 64bit host trying to perform remote debugging to an Ubuntu server which requires a remote path.  The non-normalized program path has a lower case for the drive letter returned from the launch configuration ("program": "${fileDirname}") and the normalized program path has a capital letter for the drive.  This difference causes the replacement of the local directory path to fail,  so the remotePath sent to the remote debugger is incorrect thus preventing break points from being set correctly.

Normalizes the program path that is stored in Delve object.

---

src/goBrowsePackage.ts
src/goPackages.ts

This PR fixes two things:
1. An error in `goListAll()` where we call `chunks.toString()`. The method puts `,`'s between every chunk which causes some lines to not be correct imports. I think this is why the auto-import on tab didn't work for all imports (at least for me)
2. Refactored `goBrowsePackages` so that we don't have to wait for `goListAll` to finish. This should speed up browsing packages a lot at initial time, especially for users with slower computers and very large GOPATH tree.
In `goBrowsePackages` we still need a feature that depends on `goListAll()`, which is to show a list of *all* the packages in your GOPATH to select from. So that logic is still there.

goBrowsePackages: toString bug fix + do not wait for goListAll

---

src/debugAdapter/goDebug.ts
src/goCheck.ts
src/goImport.ts
src/goPackages.ts
src/goPath.ts
src/util.ts

Fix for #840
The only scenario where we may still have issues is when somebody uses `go.gopath` to set multiple gopaths and the file/package being debugged imports pkgs from the different gopaths set in `go.gopath`. In this case, the user will have to provide GOPATH via the launch.json or set the same using the env var `GOPATH` outside of VS Code

Infer go path when debugging

---

src/goImplementations.ts

1. Not fail if guruOutput.to or guruOutput.to_method is undefined
2. If we looked for method implementation, go to method implementations only

Improvements for "go to implementation"

---

src/debugAdapter/goDebug.ts

Fix for #1178
See https://github.com/Microsoft/vscode-go/issues/1178#issuecomment-326179112

Map remote goroot to local goroot

---

src/goPackages.ts

If `go list all` emits warning messages on stderr, it seems stuck forever, and then auto completion (before importing) feature does not work. So just ignore the outputs of stderr.
It fixes #1152. And it's maybe related to #1186.

Ignore stderr outputs of go list all to fix #1152

---

.travis.yml
src/goBrowsePackage.ts
src/goCheck.ts
src/goImport.ts
src/goInstallTools.ts
src/goMain.ts
src/goPackages.ts
src/goSuggest.ts
src/testUtils.ts
test/go.test.ts

Previously the `goListAll()` cache the packages, resulting completion for newly created package not shown because the outdated cache and it quite irritating.
To takeout cache, we need to invoke `go list all` on demand. But the execution time is unacceptable, it will try to load packages from GOROOT, GOPATH and also user home directory. That is why `cp.spawn('go', [], { env: process.env })` took so long, and by not providing the env will execute faster.
Better implementation package listing tools `https://github.com/haya14busa/gopkgs`. It search the packages from golang `src`. So I replace the `go list all` using `gopkgs`.
`go list all` took 4.87s
`gopkgs` took 0.08s
- No more cache on `goListAll()` and it fast.
- Browse package also can lookup non-installed package (based on src, not the …

Show completion for newly created package.

---

src/goSuggest.ts
src/util.ts
test/go.test.ts

I put some guard for 1sec timeout for `getImportablePackages()`

Ensure completion to respond faster

---

README.md

[`go.editorContextMenuCommands`](https://github.com/Microsoft/vscode-go/blob/master/package.json#L691) is misspelled as `go. editortorContextMenuCommands` in the README.

📚 Fix misspelling of "editor context menu" setting

---

package.json
src/goCheck.ts
src/goCodelens.ts
src/goCover.ts
src/goDeclaration.ts
src/goExtraInfo.ts
src/goFormat.ts
src/goImplementations.ts
src/goInstallTools.ts
src/goLiveErrors.ts
src/goMain.ts
src/goModifytags.ts
src/goOutline.ts
src/goPath.ts
src/goReferences.ts
src/goRename.ts
src/goRunTestCodelens.ts
src/goSignature.ts
src/goSuggest.ts
src/goSymbol.ts
src/goTest.ts
src/testUtils.ts
src/util.ts
test/go.test.ts

#1142 In multi root mode
- All settings except the 2 related to language server can be set at folder level
- toolsGopath set at Workspace level will be used for all folders. If none is set at workpsace level, then the one set at any of the folder level will be used
- Language server (if enabled) will not be used when folders have different GOPATHs
- All commands and features that currently work at workspace level will work at folder level
- Build/lint/vet/test workspace
- Go to symbol in workpsace

Multi root support

---

package.json
src/goTest.ts

Fixes #1225 by adding `editor.document.save()` if the document state is dirty. Also adds a `go.saveTestFileOnRunOrDebug` (defaults to `true`) to disable auto save in the case that someone wants to disable this feature.

add auto save to tests on test run or debug

---

src/goSuggest.ts
src/util.ts

Assume the directory name is `messaging`
1. File 'main.go' => suggestion `package main`
2. File `*_test.go` => suggestion `package messaging_test`
3. File `*internal_test.go` and rest of `*.go` => suggestion `package messaging`

Package suggestion for _test.go

---

src/debugAdapter/goDebug.ts
src/testUtils.ts

we should prefer passing package name to `dlv test` or `dlv debug`. this fixes the issue mentioned at https://github.com/Microsoft/vscode-go/issues/846#issuecomment-323589274.

pass <package> to dlv test/debug if applicable

---

snippets/go.json

`t.Log(...) and t.Logf(...)` are also commonly used. I propose adding:
```json
{
"t.Log": {
"prefix": "tp",
"body": "t.Log(\"$1\")"
},
"t.Logf variable content": {
"prefix": "tv",
"body": "t.Logf(\"${1:var}: %#+v\\\\n\", ${1:var})"
}
}
```

Snippets for t.Log() and t.Logf()

---

src/goPackages.ts

Ignore sub-vendor package

---

test/go.test.ts

If user set "go.lintOnSave" to false in User settings, then tests "Error checking" and "Gometalinter error checking" are failed

Fixed tests "Error checking" and "Gometalinter error checking"

---

src/goRunTestCodelens.ts

Make the type of buildArgs executed by Codelens consistent with LaunchRequestArguments.
This fix the problem that `go.buildTags` is ignored by `debug test`.

Fix buildFlags type in 'debug test' Codelens

---

src/goSuggest.ts

Fixes #1279. Had to close/open to retrigger build (All slaves had job errors).

Support multiple parameters declared with same type when using useCodeSnippetsOnFunctionSuggestWithoutType

---

snippets/go.json

This allows VSCode users to create testable Example functions using a short snippet. It's represented by `ef` since we already have `tf` for tests and `bf` for benchmarks.
More on Example functions: https://blog.golang.org/examples.

Add snippet for Example functions

---

.travis.yml
README.md
package.json
src/goInstallTools.ts
src/goMain.ts
src/goPlayground.ts
test/fixtures/playground/main.go
test/go.test.ts

Enables the user to upload the current file or selection to the go playground using package `goplay`.
This would solve #1211

add playground command

---

src/goLint.ts
src/goVet.ts
src/util.ts

When we spawn a process to either run `go vet` or the linters, they are known to spqwn child processes of their own. Since these are on save features, multiple saves on a large project can slow things down.
This PR introduces a cancellation token that is used to kill existing vet/lint processes and their children before starting new ones

Kill existing vet/lint processes before starting new ones

---

src/goFormat.ts

On the latest insiders build it looks like the workspace config objects are now frozen (which makes sense). I don't know if there's a "more correct" way to fix this but this seemed reasonable.
Fixes #1333

Copy formatFlags before modifications

---

src/debugAdapter/goDebug.ts

#473
In a project with external dependencies, debugging hang indefinitely for me as `dlv` produces output while compiling the go code, before it starts the api server.
This caused VS Code to attempt to connect to `dlv` the api server was listening.
In order to avoid this, and to avoid arbitrary delays in the code, this change makes it so that we wait for `dlv` to declare that it's ready to accept connections before attempting to connect.
I've removed the calls to connectClient from stderr completely, as there is to my knowledge only two possible situations, both which are covered:
- Dlv starts up fine, and emits the "Api server listening" message
- Dlv crashes/exits, which gets caught by the `error` and `close` listeners.

Delay connecting to dlv until it's listening

---

package.json

It appears the template for generating a remote debugging configuration is missing.
Somewhat related to https://github.com/Microsoft/vscode-go/pull/254

Add remote debugging debug configuration

---

src/goSignature.ts

Go signature does not work for functions declared like this:
``` golang
func VeryLongLongLongLongLongName(
with int,
a int,
lot int,
of int,
parameters int) {
}
```
This patch fixes it.

Multiline func definition support for go signatures

---

snippets/go.json

statement is misspelled as "statment" at "if statement" snippet in the snippets/go.json file.

📚 Fix misspelling on snippets/go.json

---

src/goBuild.ts
src/goCheck.ts
src/goLint.ts
src/goStatus.ts
src/goVet.ts

I am also maintaining the state in the `outputChannel` which is revealed with the registered command `go.show.outputPanel` when the user clicks on the `statusBarItem` (in case the user wants debug info). Hope it is fine?

Show build/vet/lint status in Status bar. Fix #1456

---

src/util.ts

When ensuring go is in $PATH, add $GOROOT/bin, not $GOROOT, to $PATH.

Add $GOROOT/bin to $PATH for tools

---

src/goGenerateTests.ts

Implementing the first feature mentioned in #610.
This PR prevents vscode from overriding the currently open file if the test is already open in another visible editor.
To improve this even further, this could benefit from https://github.com/Microsoft/vscode/issues/15178 to even open the file if it is not visible in the other open editors.
First PR here (even first contribution to vscode) so if something is not ok, please tell me :-)

Switch to testfile if already open/visible instead of reopening

---

test/go.test.ts

Fix the broken source paths so the failing [tests](https://travis-ci.org/Microsoft/vscode-go/builds/345395708) (Gometalinter error checking and Test Linter for Package) pass. Also add an extra assert before traversing the expected errors in order to prevent an uncaught exception if no result is brought by gometalinter
@ramya-rao-a PTAL
PS: on a side note, gometalinter is not listed as a dependency for running tests locally. After I fixed the test code I realized I didn't have gometalinter installed, nor all of the required linters. I can add this info to the [wiki](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) if it is ok with you

Fix broken tests

---

package.json

Added a missing quote in the `go.vetOnSave` description.

Add missing quote in go.vetOnSave description.

---

src/goInstallTools.ts
src/util.ts

https://github.com/theia-ide/go-language-server/pull/17
Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>

Fail with better error messages if go binary cannot be found

---

src/goExtraInfo.ts

remove filter of lines starting with "\t//"
Fixes: https://github.com/Microsoft/vscode-go/issues/1550
Signed-off-by: Dan Mick <dan.mick@redhat.com>

Do not filter comment lines when hovering on structures

---

test/go.test.ts

Fixes #1547 by accepting unexpected linter diagnostics, but still performing asserts over the expected ones

Make linter tests more lax

---

README.md

Fixes the doc text for the available `Generate xxx` commands.
------
Thanks,
Gerasimos Maropoulos
Author of [Iris](https://github.com/kataras/iris)

Update README.md | fix generate* commands

---

src/goRunTestCodelens.ts

If you have two functions `TestFoo` and `TestFooTwo`, and select
'debug test' on `TestFoo`, both tests will be executed. This happens
because `go test -test.run` expects a regular expression, but we were
only passing it a function name, causing both tests to pass the regex check.
Fixed by wrapping the function name in start/end markers.
This is similar to what we do when running the tests e.g.
https://github.com/Microsoft/vscode-go/blob/3d35f45653506e14d4e98689eb22dd7fe4654478/src/testUtils.ts#L222

bugfix: Ensure 'debug test' codelens only tests the selected test.

---

src/util.ts

Errors/warnings parsed from compiler output now include column numbers in source locations.
Both source annotations and "Problems" use the column data.
Starts #1572.
Later improvements could include trying to extract further information so that annotations can be isolated to the problematic tokens instead of marking the whole line after the location column.
Probably needs testing on pre-go1.9 when the column information was not provided in compiler output.

Use col numbers from cmd outputs to give src locations for error/warnings

---

src/goRunTestCodelens.ts

Sometimes it is useful to be able to step into and debug benchmarks. This pull request adds this codelen above benchmark functions.

Add benchmark debuging codelens

---

package.json
src/debugAdapter/goDebug.ts

Hi
I added the output option for delve. 
You would be able to use delve, even if there has been `debug` directory already.
Thank you

Add the output option for the delve

---

package.json
src/goSymbol.ts
test/go.test.ts

Setting the option to true enables the user to include the standard
library located at GOROOT to be included in the results shown on
"Go To Symbol" - resolves #1567

When gotoSymbol.includeGoroot is set, also show symbols from GOROOT

---

.travis.yml

When running tests in CI, the extension is also tested against unstable
`tip`, which is supposed to show upcoming breakages. At the same time lots
of contributors are confused and deterred by builds that break for reasons
unrelated to the changeset. To mitigate this, keep testing on `tip`, but
allow failures, so it can still be used as a canary.

Allow travis failures on tip

---

src/goVet.ts

Adds build tags to the go vet command if they are present in the
workspace.
This fix is for #1591

Support build tags with go vet

---

src/util.ts

Some people might want to test the `main` package with the existence of `main.go`.
On the `_test.go` file, it will suggest `main` as package name instead of `publisher_test` or `publisher`.
Dir structure example:
```
pubsub
- cmd
- subscriber
- main.go
- publisher
- main.go
- main_test.go <-- package main
- doc.go
- pubsub.go
```
Q: Why not suggest `main_test`?
A:  Main package are not going to be reused by others, all function  might going to be non-exported. So the test package not will use the non `_test` pattern.

Fix smart package completion

---

package.json
src/goTest.ts

I took a shot at implementing #1637.

new: support for showing coverage on single function test. closes #1637

---

src/util.ts

Was broken in https://github.com/Microsoft/vscode-go/commit/be30dfc597d94194b96ae5a03ca7731a90795e8a (only for toolsEnvVars, testEnvConfig and fileEnv don't suffer from the same issue).

toolsEnvVars: Fix setting of previously unset env variables

---

src/testUtils.ts

This fixes #1626 by using the package name from the go test output combined with the workspace root folder path to expand filenames to their correct path. go test itself buffers all test output in a package until all the tests in a package have completed, so adding our own per-package buffering does not have a visible effect on the latency of test reporting.

Fix file path expansion for subpackages in go test output.

---

src/goSuggest.ts

This fixes #1287 by enabling code snippet completion of vars declared as a func type.

Use code snippets for completion of vars of func type.

---

src/goSuggest.ts

Given a type that defines a function, this change adds a code completion suggestion to expand the type into a closure. Eg:
```go
type Demo func(int) string
```
Will expand into the the suggest with the name `Demo` and upon triggering it the following snippet will be used:
```
Demo(func(${1:arg1} int) {
$2
})
```
Similarly, given the following type:
```go
type Demo func(i int) string
```
The variable name that exists will be used (`i` in this example).
If accepted, this resolves #1553

WIP: Suggestion to expand func types to func snippets (#1553)

---

src/goSuggest.ts

Fixes #1659 by checking for a line comment at the _end_ of the current line and also checking that the cursor position is within the line comment.

Fix prevention of completion popup in line comments. (fixes #1659)

---

src/goSuggest.ts
test/fixtures/completions/exportedMemberDocs.go
test/go.test.ts

This pull request adds functionality described #1005 by triggering autocompletion in comments if the next line is an exported member. This would be handy in adding documentation for exported members.

Triggering autocompletion in comments if the next item is an exported member #1005

---

package-lock.json

Right now this repo seems to not check in `package-lock.json`. Still it will be created on each `npm install` (which has me undo each commit at least once :jack_o_lantern:). This would prevent npm from generating a lockfile.
Alternatively we could also check in the lock file (personally I'm very undecided about what is the better option in this context).
I just think it'd be a nice addition to prevent accidental check-ins of `package-lock.json`  from happening.

Add package-lock.json to source control

---

src/goCover.ts

This fixes #1683 which was causing the code coverage coloring to be incorrect.
Full explanation there, but the short version is that the 8th column is not a boolean but a coverage count. This adjusts that test and a couple of comments.

Fixes #1683; column 8 is the coverage count, not a boolean

---

README.md
package.json
src/goInstallTools.ts
src/goMain.ts

Instead of using go-code, use go-languageserver for providing
code completion results when enabled. Solves #1593

When using go-languageserver, also use code completion feature

---

.vscode/launch.json
package.json
src/debugAdapter/goDebug.ts

Initial integration to v2 api for #1555. This includes additional debugger options for launch configuration

(WIP) Delve v2 API debug adapter

---

README.md
package.json
src/goInstallTools.ts
src/goLint.ts

There are some small improvements over https://github.com/Microsoft/vscode-go/pull/1692

Add support for golangci-lint as the lintTool

---

README.md
package.json
src/goInstallTools.ts

Introduces support for revive. Revive is an extensible, configurable, and faster alternative of golint.

Add support for revive as lintTool

---

src/goLint.ts
src/goVet.ts

When a lint tool takes a non-trivial amount of time to execute (e.g. gometalinter), and the user has `lintOnSave` enabled, saving a file twice in quick succession causes the previous lint tool execution to be cancelled.
However, subsequent executions of the lint tool will be [terminated immediately](https://github.com/Microsoft/vscode-go/blob/2075d98808e10bbe475500e2a1752d3790e55251/src/util.ts#L584) because the "global" CancellationTokenSource used for cancelling the lint tool is still in the cancelled state.
This is fixed by recreating the CancellationTokenSource after it has been cancelled.

Fix lint tool cancellation

---

src/goSuggest.ts
test/fixtures/completions/exportedMemberDocs.go
test/go.test.ts

When testing for #1698 noticed that completion in comments was not triggered for exported methods on structs. Modified the regex to capture this condition and added test to check for appropriate function in triggering completions.

Triggering Completion of Exported Methods on Structs

---

src/goSuggest.ts

Avoid adding snippet for function suggest when cursor is followed by (). Fixes #1655

Avoid duplicate function parameter body on function suggest snippets

---

src/goPackages.ts

This should ignore any import of internal packages on the root such as:
```
internal/syscall/windows/registry
internal/nettrace
internal/singleflight
internal/cpu
internal/testenv
internal/trace
internal/testlog
internal/syscall/windows/sysdll
internal/syscall/windows
internal/syscall/unix
internal/poll
internal/race
```

Disallow import internal root package

---

.travis.yml
src/goInstallTools.ts
src/goSuggest.ts

As package nsf/gocode is unmaintaned this is now consuming mdempsky/gocode.
In order to cater for changes, correctly handle empty results and promise
rejections.
This would solve #1645 although for reasons unclear to me, the updated `gocode` package will not provide any results for members of unimported packages (hence the skipped test case). Don't know if this is a dealbreaker or can be fixed deeper down in `goSuggest.ts`.

Migrate from nsf/gocode to mdempsky/gocode for completion results

---

src/goRunTestCodelens.ts
src/goTest.ts
src/testUtils.ts

This adds support for tests using the widely used [stretchr/testify](https://github.com/stretchr/testify) framework, and allows running and debugging individual test methods with instances which use github.com/stretchr/testify/suite interfaces.

Added support for tests using stretchr/testify

---

package.json
src/goDebugConfiguration.ts
src/goRunTestCodelens.ts
src/util.ts

This PR adds a new runtest.debugConfig setting inside of go.enableCodeLens that mimicks the launch.json options for delve, so we can configure the test debugger
Fixes #1735 
An example user setting using this feature:
```json
"go.enableCodeLens": {
"runtest": true,
"runtest.debugConfig": {
"useApiV1": false,
"dlvLoadConfig": {
"followPointers": true,
"maxVariableRecurse": 1,
"maxStringLen": 128,
"maxArrayValues": 128,
"maxStructFields": -1
}
}
},
```

Add debug configuration options for test debug codelens

---

.vscode/launch.json
package-lock.json
package.json
src/avlTree.ts
src/goFormat.ts
src/goOutline.ts
src/goPath.ts
src/util.ts
test/unit/NNDict.test.ts

This removes massive copy overhead from recreating Buffers of the entire document for every symbol in the file. Also reduces the quadratic time approach to converting from byte-offsets to character-offsets to log-linear time.
Hopefully closes #1668.

Increase overall performance by speeding up GoDocumentSymbolProvider

---

src/goSuggest.ts

As per the suggestion: https://github.com/Microsoft/vscode-go/issues/1779#issuecomment-403675528
This PR disables suggesting function parameters if passing the suggestion as an argument. If cursor ends with `,` or `)` it skips parameter suggestion.
For more info: https://github.com/Microsoft/vscode-go/issues/1779

Do not suggest function parameters if passing it as an argument

---

src/goPackages.ts
src/goSuggest.ts

This PR will make it so that "import suggestions" will always put your project's packages at the top. This really helps when there are very common package names like `log` or `errors` and you want to import them through the autocomplete feature. Before this pr, you'd have to scroll through 10s if not 100s of packages to find the one form you're workspace. 
From the screenshot below, you can see that if you're inside `upspin.io`'s sourcode, then the autocomplete shows you imports from that package first.

Prioritize current project import suggestions

---

src/debugAdapter/goDebug.ts

@ramya-rao-a 
This should make delve errors more identifiable that just the standard error messages

Include delve error in apicall error logs

---

src/goDebugConfiguration.ts

use regex to check if the current file is for test

Add auto `test` debug mode for launch.json (#1780)

---

src/goBuild.ts
src/util.ts

Make temporary build filename user specific to prevent conflict on systems with shared temp folders

---

src/goFormat.ts

Currently, I'm getting a `spawn EACCES` error, but the console is reporting it as `TypeError: err.startsWith is not a function` because the `err` variable is an object and doesn't have the `startsWith` method.

Fix error handling for when err is not a string

---

package.json
src/goMain.ts
src/goTest.ts
src/testUtils.ts

This PR adds a new command called "go.benchmark.package" that runs benchmark tests for the current package.
I did this adding a new isBenchmark flag to the testCurrentPackage file. 
Also, according to [this](https://golang.org/cmd/go/#hdr-Testing_flags) docs, the `-bench` flag doesn't have a default value and by default doesn't run any tests. I've edited the testConfig to send `.` when it is running for a package.

Add command: "Go: Benchmark package."

---

src/goOutline.ts
test/fixtures/outlineTest/test.go
test/go.test.ts

Do not show blank identifiers in file outline

---

snippets/go.json

Make iferr and forr snippets a bit more convenient.

---

src/debugAdapter/goDebug.ts
src/goBuild.ts
src/goCheck.ts
src/goCover.ts
src/goMain.ts
src/goTest.ts
src/util.ts

Closes #1905.
This closely mirrors the [official TypeScript extension's implementation](https://github.com/Microsoft/vscode/blob/ad68ff316c472aea4acfa31b3a5bab3b101d968b/extensions/typescript-language-features/src/utils/electron.ts#L17), which does not persist the directory path for reuse between activations.
@ramya-rao-a, making the directory path persistent is pretty hacky and not the convention for any of the official extensions I've seen, so I've left it out (let me know your thoughts on this).

Use mkdtemp for secure temp files

---

src/goSuggest.ts
test/fixtures/completions/unimportedMultiplePkgs.go
test/fixtures/fillStruct/golden_2.go
test/go.test.ts

Added completions for symbols from unimported pkg if there are multiple matches for pkg name

---

src/testUtils.ts

Fix testify not being detected anymore

---

snippets/go.json

This should cover the `iferr` snippet for
1. non-returning value
2. return single value
2. return 2 values
3. return nil, err (by default)

Better  snippet

---

src/testUtils.ts

This is regarding https://github.com/Microsoft/vscode-go/issues/1534
The patch re-orders the user-provided flags and appends them at the end before passing to `go test`. This way, flags using `-xargs` do not interfere with the defaults flags.
An example is the use of a flag consumed by glog `-v=4` which would interfere with the `-v` of the `go test` command. The glog flag has to be passed via `-xargs` before the `-v` controlling the verbosity of the test output.

chg: user provided flag handling when running tests

---

src/goMain.ts

commands added :
* Go to definition
* Go to implementation
* Go to symbol in file
* Go to symbol in workspace
fixes #1822

goMain.ts add commands to Go: Show All Commands

---

package.json
src/goCheck.ts
src/goLint.ts
src/goMain.ts

- Adds the feature described on Issue [1931](https://github.com/Microsoft/vscode-go/issues/1931) - enabling lint on save on an individual file basis
I sideloaded the extension then tested the following linters in `"go.lintOnSave"` `file` mode by adding some unused variables and uncommented functions in a Go project.
- `golint`
- `gometalinter`
- `megacheck`
- `golangci-lint`
- `revive`
Please let me know if there's anything I've overlooked or if anything be improved. Thanks!

Add 'file' option for lintOnSave setting

---

src/goSuggest.ts

This PR changes the autocomplete dialog to use more icons, distinguishing structs, interfaces and other types.
Before:
After:
The following code is used in the autocomplete example above:
```
type BoolType bool
const Const = 8
func Func() {}
type Interface interface{}
type StringType string
type Struct struct{}
var Var = 9
```

Use more icons in autocomplete box

---

src/goInstallTools.ts

since last commit, when installing, output shows:
```
Installing 13 tools at /home/ying/Documents/sources/toolsForGolang/bin
gocode
gopkgs
go-outline
go-symbols
guru
gorename
dlv
gocode-gomod
godef
godef-gomod
godoc
goreturns
golint
Installing github.com/mdempsky/gocode SUCCEEDED
Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/derekparker/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing github.com/ianthehat/godef SUCCEEDED
Installing undefined FAILED
Installing …
```

delete unneeded godoc

---

src/goInstallTools.ts

https://github.com/Microsoft/vscode-go/issues/1966

use last gopath element when installing tools

---

README.md

Fixed typo: wrong type of 'palette' (was 'command pallet')

Fixed typo: wrong type of 'palette'

---

test/go.test.ts

I've checked the travis pipeline is broken because of [these changes](https://github.com/Microsoft/vscode-go/commit/d789de0f9561a1c9aa979a145cb64bcbfbe185cf)
The `items` variable now can be of 2 different types: `[]CompletionItem` or `CompletionList`.
[Check here](https://travis-ci.org/wachino/vscode-go/builds/442320520?utm_source=github_status&utm_medium=notification) to check now the pipeline works fine

Fix go tests variable can be array of completionitem or a completionlist

---

.vscode/launch.json
.vscode/tasks.json
README.md
package.json
src/util.ts

Detail: https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

Update #workspaceRoot variables reference

---

src/goSuggest.ts

Removed to allow suggestions on platform-specific syscall like `syscall/js`
<s>WORK IN PROGRESS! Still undecided on how to resolve packages without precompiled objects.</s>

Remove env mask on GOOS and GOARCH

---

.vscode/launch.json
.vscode/tasks.json
src/debugAdapter/.vscode/launch.json
src/debugAdapter/Readme.md

I was trying to tackle #1529 and while trying to follow the guide from https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter I faced a few errors and saw an old task that had deprecated options. This pr fixes those issues and updates the task's option according to the recent spec.

fix: Fix debug debugger tasks and guide

---

src/goBuild.ts

Instead of running go build for each package in workspace,
add all packages directly to it.
Closes #1890

Pass list of packages at once when running go build

---

README.md

Changed "Go meta linter" to title case as it is in the previous paragraph. Changed "OS X" to "MacOS" since this is the newer name of that operating system. Added a missing period.

Tiny README changes

---

CHANGELOG.md
src/debugAdapter/goDebug.ts
test/fixtures/gogetdocTestData/test.go
test/go.test.ts

- Spelling: wouldnt => wouldn't, couldnt => couldn't
- Removal of trailing whitespace.

Fix spelling of contractions wouldn't and couldn't

---

src/goCover.ts

Following the suggestions described on issue https://github.com/Microsoft/vscode-go/issues/2045
Similar to the function [updateCodeCoverageDecorators](https://github.com/Microsoft/vscode-go/blob/master/src/goCover.ts#L73) the `applyCodeCoverage` function now disposes of any existing decorators before applying new ones.

Diposing decorators before applying new ones for code coverage.

---

src/debugAdapter/goDebug.ts

Fix for #1990

---

src/goSuggest.ts

Using `go doc` instead of `godoc` due to https://github.com/golang/go/issues/25443 (plus `godoc` doesn't show doc for unexported identifiers nor for anything in a main package)
`go doc` doesn't seem to support giving the code of an unsaved file via stdin like `gocode`, so it won't display documentation for unsaved changes.
Fixes #194 
cc @ramya-rao-a

Add item documentation to completions

---

src/debugAdapter/goDebug.ts

See #1989 
This displays the address of the variable the pointer is pointing to (for pointer comparison). It also allows expansion in the debugger.
Example code:
```
package main
import "testing"
func TestX(t *testing.T) {
var i, j int
i = 0
j = 1
k := []string{"asdf"}
var p = &i
var q = &j
var r = &k
t.Logf("%#v %#v %#v", p, q, r)
}
```
Shown in debugger:

Improve debugging of pointer values

---

package.json
src/goSuggest.ts

A recent addition broke module-enabled gocode (gocode-gomod binary which is the github.com/stamblerre/gocode fork) 
Unrecognized flags cause errors, so this change only adds this flag to the binary that recognizes it (mdempsky/gocode)

Fix module enabled gocode

---

package.json
src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Fixes #946
This still has a maximum depth of 50. Delve has no way to specify an infinite max depth, or query the length of the stacktrace.

Add stacktrace paging support to debug adapter

---

src/goOutline.ts
test/fixtures/outlineTest/test.go
test/go.test.ts

This PR fixes the code outline from erroneously displaying structs as interfaces.
Before 
After

Differentiate between interfaces and structs in outline

---

src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Include buildFlags and args when running without debugging. Use current file (if there is one) when 'running without debugging'.
Fixes #2086 and #2085

Fix 'Debug: Start Without Debugging' to use current file and include buildFlags/args

---

src/goMain.ts
src/goTypeDefinition.ts
test/go.test.ts

Go to Type Definition command implementation. Works with latest guru [with this commit](https://github.com/golang/tools/commit/9c8bd463e3aca40b6288cd14f7b7703206ff743b).

Go to Type Definition command implementation

---

src/testUtils.ts

Fixes #2144: add brackets around the values in regexp

wrap values choice in brackets

---

src/goMain.ts
src/goSuggest.ts

Note that the extension doesn't actually start the gocode daemon,
the gocode client itself does that as necessary.
It is safe to close the daemon for the same reason however.
If other clients were using the daemon, it will be restarted
on their next request.
Fixes #2132

Close gocode daemon on deactivation

---

src/debugAdapter/goDebug.ts

It seems that defaults from the debugger `configurationAttributes` in package.json are only used for auto-complete, and won't be filled in automatically if not given.
Fixes #2187, and fixes #2196

Default stackTraceDepth to the value from package.json

---

src/debugAdapter/goDebug.ts

According to the spec you are first supposed to acknowledge the command and only than send the stopped event. Changing this seems to have fixed the jumping to `gopark`/`proc.go` for me. Please test that this works.
Debugging is still really slow, but that's a different issue, VS Code is simply requesting, and receiving, way too much information from delve on each step.
See: [Debug Adapter Protocol Specification - Next Request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Next).
Possible fix for #2133

Attempt to fix the debugger jumping to gopark

---

package-lock.json
package.json
src/debugAdapter/goDebug.ts

Use LoggingDebugSession instead of vscode-debug-logger

---

src/debugAdapter/goDebug.ts

Whoops, vscode-go was actually already sending the response first. This PR was wrong and should be reverted. It probably caused the gopark issue to happen less because VS Code got stuck on the continue/next/etc taking a long time waiting for the actual break to happen.
This reverts commit 456fdab49f3e211ddb310c1abb4443c5dadd6c0f.
@ramya-rao-a

Revert "Attempt to fix the debugger jumping to gopark (#2207)"

---

src/goDeclaration.ts
src/goSuggest.ts
src/util.ts

See https://github.com/mdempsky/gocode/commit/be056ad32a5e9e6b0f640e650319100c464e19a7
Part of #2107 
P.S. I already made the PR to godef too: https://github.com/rogpeppe/godef/pull/105

Use the newly added receiver output from gocode to get the correct documentation

---

src/goPath.ts

- Updates the `fileExists` function to do the additional executable check via [fs.accessSync](https://nodejs.org/docs/latest-v7.x/api/fs.html#fs_fs_accesssync_path_mode) using Node's [file access constants](https://nodejs.org/api/fs.html#fs_file_access_constants).
Potential fix for #2220

Expand functionality of `fileExists` function with executable check

---

README.md
package.json
src/goInstallTools.ts

- Remove deprecated megacheck
- Add staticcheck instead

Add staticcheck fixes: #2231

---

src/goDeclaration.ts

Use the newly added receiver output from godef to get the correct documentation
See rogpeppe/godef#105
Part of #2107
⚠️ Depends on https://github.com/Microsoft/vscode-go/pull/2215 and the godef PR being merged

Use the newly added receiver output from godef to get the correct documentation

---

src/goCover.ts

This pull request partially fixes #1852.

Code coverage removal fix for single line comments

---

src/goSuggest.ts

Resolves #2063 - only suggest the exported member name if the current comment has no content.

#2063 only suggest exported member name at start of comment

---

src/goDeclaration.ts
src/goMain.ts
src/goModules.ts
src/goSuggest.ts
src/util.ts

Right now, we use the workspace folder as cwd when running godef and gogetdoc for the Go to definition feature. 
This might not be performant if the workspace folder is much higher than where the go.mod file is
This might not give accurate results in case of sub modules
Also, when running `go doc` to get the documentation to show on hover, we don't set any working directory at all. This results in getting no documentation for symbols in the same package.
This PR updates the code that runs `godef`, `gogetdoc` and `go doc` to use the folder corresponding to the right go.mod file as cwd
When operating on files under the module cache, we use the workspace folder as before
Not using the right package import path for packages in module cache, results in no documentation to show on hover for …

Use folder containing go.mod file as cwd when running godef, gogetdoc, go doc

---

.travis.yml
src/debugAdapter/goDebug.ts

Ensure that shadowed variables have a unique name so they are properly
displayed in the variables pane.  Each nested scope will enclose the
variable name in a pair of parentheses.

Fix display of shadowed variables while debugging

---

src/debugAdapter/goDebug.ts

**Issue**
Can't set/remove breakpoints while debuggee is running
**Details**
Implemented **stop-breakpoint-start** approach to resolve the issue as described in https://github.com/Microsoft/vscode-go/issues/978#issuecomment-361015995.
Take a look at #978 for details, @muravjov's comments contain detailed description what's going wrong in that case.
Fixes #2002

debug: fix updating breakpoints while debuggee is running

---

src/goInstallTools.ts

Seems like the repository link of `dlv` has changed and the plugin is unable to download it, this should fix it, probably. :smile:

Updated the dlv repository link

---

src/debugAdapter/goDebug.ts

Fixes #978 
**Addressed issues**
* Should maintain alive threads list and update it on 'ThreadsRequest'
* Should update `debugState` and `threads` on 'PauseRequest'
* Returning an empty array on `threads` request. VS Code expects that a process consists of at least one thread
* Unhandled exception in `handleReenterDebug` in case of `this.debugState.currentGoroutine` is unitialized
* Unhandled exception in `threadsRequest` when `this.debugState` is unitialized

debug: fix 'pause' command

---

src/debugAdapter/goDebug.ts

If a variable contains children but they have not been loaded issue an
expression command to delve to fetch them, then update the variable's
children array with the result.  This required refactoring the
evaluateRequest method into two parts so that delve expressions can be
evaluated synchronously.
Removed unreferenced param in convertDebugVariableToProtocolVariable.

debug: Display nested content in the variables pane

---

src/goCover.ts
src/goTest.ts

Fixes #2193 by showing coverage in files even if the test fails

Show coverage for files when tests fails

---

src/debugAdapter/goDebug.ts

When evaluating a global variable VS Code will omit the frame ID
argument, so default to the topmost frame of the current goroutine.

Fix evaluation of global variables

---

package.json
src/debugAdapter/goDebug.ts

The 'go list' command is expensive so the result should be cached.
There was a cache in place but it wasn't being populated.

Cache results of 'go list' when fetching package info to get package variables

---

src/debugAdapter/goDebug.ts

Only read from args.showGlobalVariables if it has a boolean value.

Fix default value for showGlobalVariables

---

src/goCover.ts

- Passes the uri of the current active file for `coverageDecorator` config
fix for #2264

Provide coverageDecorator config via editor uri

---

CHANGELOG.md
src/debugAdapter/goDebug.ts

Delve doesn't load strings or arrays or slices whose length is greater than 64. This value can be changed by using the setting `dlvLoadConfig` whose default values are as follows
```
"go.delveConfig": {
"dlvLoadConfig": {
"followPointers": true,
"maxVariableRecurse": 1,
"maxStringLen": 64,
"maxArrayValues": 64,
"maxStructFields": -1
}
}
```
In https://github.com/Microsoft/vscode-go/pull/2198, we added the ability to expand nested content in the variables pane to fix https://github.com/Microsoft/vscode-go/issues/1010.
But while providing the feature to expand nested content, we also ended up expanding arrays and strings that have length > 64 if the said arrays/strings are children of one of the variable.
This PR restricts such expansion to just structs and interfaces

Expand nested content only for non array, maps

---

src/goExtraInfo.ts
test/go.test.ts

Extracted from https://github.com/Microsoft/vscode-go/pull/2245. Hopefully the merge/rebase back into it won't be too difficult...

Remove the deprecated MarkedString

---

.vscode/settings.json

- when opening the project in VsCode, use TS that is brought in as a dependency since that is what it will build it

use TS from dependencies when running in vscode

---

src/debugAdapter/goDebug.ts

In CTRL-F5 scenario delve isn't running so don't try to halt it.

Fix crash in start without debugging scenario

---

src/debugAdapter/goDebug.ts

Per Delve documentation type names should be enclosed in quotes; this
fixes parsing of type names with e.g. '-' characters in them.

Fix loading of child types

---

src/goSignature.ts

Fixes #1682 
I noticed (just after pushing my branch) that there already is an util function [here](https://github.com/Microsoft/vscode-go/blob/0.6.82/src/util.ts#L289-L299) that uses regexes. I didn't run any benchmarks comparing performance (assuming both methods work the same)

Don't count signature position changes inside string literals

---

src/debugAdapter/Readme.md

Minor improvements, and includes a section on how to debug both VS Code and the extension debug adapter

Update debug adapter README

---

src/debugAdapter/goDebug.ts

@ramya-rao-a PTAL. I found this while examining #2205
Maybe this was partially related to the issue @jhendrixMSFT saw on #2288
Repro code:
```go
package main
import "fmt"
func helloworld() string {
return "Hello World!!"
}
func main() {
a := "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasdeefea"
b := []byte(a)
m := map[string]int{"1": 1, "2": 2, "3": 3}
fmt.Println(helloworld() + a + string(b) + fmt.Sprintf("%v", m))
}
```
Without these changes, the Copy Value action will fail on the watch view for all children of b and m

 Fix expression name mapping on debug views

---

package-lock.json
package.json
src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Before, this option was only available in `launch.json` but this PR makes `showGlobalVariables` as a workspace level setting so that things like the debug and run test actions can use this setting.

Added showGlobalVariables as a workspace level parameter

---

package.json
syntaxes/go.mod.tmGrammar.json
syntaxes/go.sum.tmGrammar.json

For: https://github.com/Microsoft/vscode-go/issues/1886
I was 90% done with this before I realized there was already a PR out there from a few months ago. If this isn't useful, feel free to close.

add go.mod and go.sum support

---

package.json

Hi,
There were some single quotes in use for the JSON config file examples.
As JSON doesn't allow single quotes the UI was returning the error "[jsonc] Value expected" if they were copy-pasted. This was a little bit confusing.
Thanks

Fix single quotes uses for JSON examples.

---

snippets/go.json

For anonymous go function (the snippet with the prefix "go") I think it will be more convenient if we end snippets in the body instead of the variable field. The function body is the largest of these 3 placeholders and will be in need of completion features more than any other. Therefore, I think, it is reasonable if we give it the $0 place.

Changed swapped $2 and $0 position for anonymous go function snippet.

---

.vscode/launch.json
package-lock.json
package.json
src/goGenerateTests.ts
src/goImport.ts
src/goOutline.ts
src/goPackages.ts
src/goReferencesCodelens.ts
src/goRunTestCodelens.ts
src/goTest.ts
src/testUtils.ts
test/go.test.ts

Move to DocumentSymbol

---

package-lock.json
package.json
src/debugAdapter/goDebug.ts
test/go.test.ts

- execute detach even when halt has failed. Fixes #2265

Fix debug file not getting deleted

---

README.md

README: add link to commands for people new to vscode

---

src/goMain.ts

When switching between workspaces with different goroot and toolsGopath
settings, the editor is suggesting that re-compiling tools is required
because the GOROOT state is global and not toolsGopath-aware.
This makes the global context a map keyed on toolsGopath.

Make tools re-compiling warnings scoped by toolsGopath

---

README.md
package.json
src/goCheck.ts
src/goInstallTools.ts
src/goMain.ts
src/goModules.ts
src/goPath.ts
src/goSuggest.ts
src/util.ts

Now that the language server from Google is ready for use, there are some changes needed in the Go extension to ensure good user experience
- Allow installing of the gopls language server using `Go: Install/Update Tools`
- Prompt users who use the language server from Sourcegraph to switch to the one from Google
- Disable build on save feature when using gopls or bingo to avoid duplicate errors
- Enable format and auto-completion features from the language servers
_Edit as per latest commits:_
- If using modules but not any language server, users will now be prompted to install and use `gopls`
- If using Sourcegraph, users will now be prompted to install and use `gopls` or stop disable the `go.useLanguageServer` setting
- For anyone setting `go.useLanguageServer` for the first time, …

Use gopls for language server

---

src/debugAdapter/goDebug.ts

For cases of `args: []` in launch.json, an empty `--` is sent to delve on the command line. This check fixes any potential issue this may cause in future versions (like setting extra parameters after args in the debug adapter)

Do not send empty param to delve on empty args

---

README.md

Previously you'd click the release notes link, get redirected to [here](https://github.com/Microsoft/vscode-go/wiki/Release-Notes), and then have to follow an additional link to view the [changelog](https://github.com/Microsoft/vscode-go/blob/master/CHANGELOG.md). This PR removes the middle step.

Update link to changelog

---

package-lock.json
src/goSignature.ts
src/goSuggest.ts
src/util.ts

Fixes (at least part of) #2481

Don`t process function signatures on comment lines

---

package-lock.json
package.json
src/goMain.ts

also forward go.mod and go.sum files to the language server
This is to allow the experiment in https://go-review.googlesource.com/c/tools/+/174949

Add incremental sync experimental option

---

package.json
src/goMain.ts

The issue of stuck diagnostics seems to be solved, so we can now enable diagnostics by default.
Also, adds configurability for documentLink, which seems to have been requested by a few people, both on the issue tracker and on Slack.

support disabling document links, enable diagnostics by default

---

src/goVet.ts

Closes #2527 
This PR add ${workspaceRoot}, ${workspaceFolder} and ~(except Windows) resolution for `-vettool=` or `--vettool=` in `go.vetFlags`.
I've prepared sample analyzer repository(https://github.com/tamayika/analyzer).
1. Clone https://github.com/tamayika/analyzer
2. Build it
3. Launch vscode-go in debug mode and open github.com/tamayika/analyzer
4. See go vet result(if you can not see,  edit go file and save it.)
Sample image:

Add workspace resolution for -vettool in go.vetFlags

---

package.json
src/goMain.ts

This seems pretty straight forward, and does actually work. I would ask that this included for the time being in some form. Please let me know what you thing of this. I originally thought about adding some logging around it, but I didn't spot any example code on how to do just that.
This should resolve #2500

Add command to restart language server

---

syntaxes/go.mod.tmGrammar.json

I believe this will fix the issues identified in #2423 .
A space is no longer required after the directive, so both
```require// this is now a comment```
and
```require(```
should be matched.
Comments will also be detected within unquoted strings:
```
module k8s.io/kubernetes// this is now a comment
```
Which I believe replicates this line from the parser: https://github.com/golang/go/blob/master/src/cmd/go/internal/modfile/read.go#L546.
Finally anything unmatched is marked as invalid.

go.mod: allow no space before comment, do not allow double slash in unqouted string

---

src/goPath.ts
src/util.ts

This is a feature I'd like, raised an issue describing it [here](https://github.com/microsoft/vscode-go/issues/2543)

feat: allow workspaceFolder substition in go.alternateTools

---

package.json
test/unit/NNDict.test.ts

I noticed that the `npm run lint` command was not covering all the typescript files in the repo and was therefore missing some linting errors. I have changed this command and the `npm run fix-lint` command so that they use the tsconfig.json file to determine which files will be linted. I have also used the fix-lint command to fix the errors which my change had uncovered.

Use tsconfig.json to determine which typescript files to lint

---

src/goBaseCodelens.ts
src/goInstallTools.ts
src/goMain.ts
src/goModules.ts
src/goOutline.ts
src/stateUtils.ts
src/testUtils.ts
src/util.ts
test/utils.test.ts
tslint.json

This enables one of the commented out linting rules and fixes all the new linting failures by using `npm run fix-lint`.

Turn on the "no-consecutive-blank-lines" linting rule

---

package.json
src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Related: #1599 #1609 
The reason is that sending `halt` request twice when close `delve` session.
This PR add support for `"request": "attach"` in `launch.json`. You can attach a running process from `dlv --headless` remote server, and detach without kill the running process.
I'm not a `TypeScript` beginner even, so the code modified maybe ugly, but it works. It's wonderful if anyone improve the code.

Supoort attach/detach remote headless server without kill process

---

src/goDebugConfiguration.ts

There was a comma missing on this GDPR annotation which caused VS Code's telemetry tooling to fail when extracting the events.

Fixed GDPR annotation

---

src/goModules.ts

This change clarifies that gopls is experimental when prompting the user.

goModules: change gopls prompt message

---

README.md
package-lock.json

Include TOC within [README.md](https://github.com/microsoft/vscode-go/blob/master/README.md) for better navigation.

feat(docs): Include Table of Contents

---

package.json

This is to allow configuring an alternate path for gopls as well. Everything else in the extension is ready for this configuration, but the configuration feature itself is missing. By "ready" I mean these lines:
https://github.com/microsoft/vscode-go/blob/4b516f9a872f3a3086d6d56f8e346d4b5a7e53ef/src/goInstallTools.ts#L559
https://github.com/microsoft/vscode-go/blob/4b516f9a872f3a3086d6d56f8e346d4b5a7e53ef/src/util.ts#L375

Added configuration for alternate gopls path.

---

src/goStatus.ts

I saw that Travis has been throwing this error on recent builds:
```
Go Extension Tests
Activating extension `ms-vscode.Go` failed:  Cannot read property 'document' of undefined
Here is the error stack:  TypeError: Cannot read property 'document' of undefined
at Object.showHideStatus (/Users/travis/gopath/src/github.com/microsoft/vscode-go/src/goStatus.ts:33:24)
at activate (/Users/travis/gopath/src/github.com/microsoft/vscode-go/src/goMain.ts:328:2)
at Function._callActivateOptional (/Users/travis/gopath/src/github.com/microsoft/vscode-go/.vscode-test/vscode-1.36.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:518)
at Function._callActivate (/Users/travis/gopath/src/github.com/microsoft/vscode-go/.vscode-test/vscode-1.3 …
```

Make showHideStatus handle an undefined editor

---

package-lock.json
package.json

`gopls` has added support for features like `textDocument/prepareRename`, which is only available with more recent versions of the vscode-languageclient.
Fixes https://github.com/microsoft/vscode-go/issues/2714

update vscode-languageclient version

---

.travis.yml
README.md
package.json
src/goInstallTools.ts
test/integration/extension.test.ts

`gometalinter` is deprecated and the suggested replacement is `golangci-lint`, I followed the steps told by @ramya-rao-a in https://github.com/microsoft/vscode-go/issues/2509#issuecomment-526040863 (thank you).

Remove deprecated gometalinter

---

languages/go.mod.language-configuration.json
package.json

`go.mod` files support "//" line comments, but not "/*" block comments.
This will enable the "Toggle Line Comment" command for example.

Add line comment language configuration for go.mod

---

src/goLanguageServer.ts

Hard-coding latest version info for gopls for now while we explore if using go proxy as the source of truth for the `gopls` version info is the right approach or not
cc @stamblerre

Hard-code latest version info for gopls

---

src/debugAdapter/goDebug.ts

This will fix issue https://github.com/Microsoft/vscode-go/issues/2119. The bug is that we are stripping either forward or backward slashes even if they are by themselves.

Fix a bug where remoteSource is incorrect if it is a forward slash

---

package.json
src/debugAdapter/goDebug.ts

Send a dummy thread to vscode when stopped on entry as there are no
threads in the process yet.
Send the stop event with the same dummy thread ID.

fix stopOnEntry

---

.travis.yml

After travis-ci moved their default linux os from trusty to xenial, `xvfb` has to be started differently.
Closes #2779

Fix and reenable linux in travis runs

---

src/goDoctor.ts

Currently the placeholder text when extracting a function or a variable is
> Please enter a name for the extracted variable.
With this change, in the case of extracting a function, the placeholder text will be
> Please enter a name for the extracted method.

Show correct placeholder when extracting method

---

.travis.yml

Yaml doesn't support inline comments on multiline strings (#2802), unfortunately. 
Travis can't parse the file correctly and stops running builds. 
I saw it too late, after #2802 already got merged.
This PR should amend this.

Move comment outside multiline command in .travis.yml

---

src/goInstallTools.ts

Go 1.11 still requires a `go.mod` file to download in module mode. Support it by adding a fake `go.mod` file to the temporary directory for tool installation.

support Go 1.11 when installing tools in module mode

---

test/integration/extension.test.ts

- Allow integration tests to run with the default GOPATH of ~/go.
- Display user-friendly positions in test failures
Updates #2805

Clean up the signature help test

---

package.json
src/goLanguageServer.ts
src/goMain.ts

As seen in #2768 and #2767, the implicit calls to https://proxy.golang.org/golang.org/x/tools/gopls/@v/list can fail in multiple scenarios.
In VS Code, we also want to follow the guideline of not making any outgoing calls over the network unless it is done as part of a feature resulting from an explicit user action which the user is aware of.
Exceptions to this rule should be documented and a setting should be provided for the user to opt in/out.
Keeping this in mind, the recent feature of making calls to https://proxy.golang.org/golang.org is being updated as follows in this PR
- Provide a setting to opt in to the automatic update check. This is similar to the `extensions.autoCheckUpdates` setting in VS Code
- If the above is not enabled, then hard-code the latest known latest version of …

Gate the check for gopls updates using a setting

---

src/goInstallTools.ts

Running other `go` commands in the installation directory requires a `go.mod` file (this fixes the issue described in https://github.com/microsoft/vscode-go/issues/2811#issuecomment-544101197).
We should always use a fresh directory for installations in case versions change across multiple installations.
Fixes https://github.com/stamblerre/gocode/issues/40

Always use a fake mod file and fresh temp directory for installation

---

src/debugAdapter/goDebug.ts

Distinguish between nil and zero length slices and maps

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Templates make it easy to understand what is happening.

Use new templates

---

src/debugAdapter/goDebug.ts
src/util.ts
tslint.json

Part of fixing #2333.
I've tried to handle errors in the same way as other areas of each file.
I've operated under the assumption that logging errors is better than
silently dropping them.

tslint: add no-empty

---

src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts
src/goMain.ts
src/goModules.ts

This PR attempts to fix the issue in #2828 where code under GOPATH gets debugged under the assumption that we are not in module mode if GO111MODULE is not `on`.

Use  mod file to determine module mode when debugging

---

README.md

- Changed the link to the `gopls` wiki
- Added link to the `VSCode`-specific settings page of `gopls` wiki

Update gopls wiki links

---

src/goLanguageServer.ts

This change makes sure that we don't update users to pre-release versions of `gopls`.

Exclude prerelease tagged versions when fetching latest gopls version

---

src/goInstallTools.ts

This prevents modifications to the `go.mod` file from affecting other tool installations.

run `go mod tidy` between tool installations

---

package.json
src/goTest.ts

add single file coverage

---

package-lock.json
src/goMain.ts

Add option for "Don't Ask Again" while saving the file in debug mode

---

package.json

Activate extension when workspace contains go files

---

src/goInstallTools.ts
src/goTools.ts

Fixes https://github.com/microsoft/vscode-go/issues/2936

install tools with wildcards in module mode for Go >= 1.13

---

src/goInstallTools.ts

Running `go mod tidy` is more error-prone than just deleting and recreating the file.
Fixes https://github.com/microsoft/vscode-go/issues/2936.

delete and recreate go.mod instead of running go mod tidy

---

src/goOutline.ts
test/fixtures/outlineTest/test.go
test/integration/extension.test.ts

* pending merge by github.com/ramya-rao-a/go-outline, sent pull request at https://github.com/ramya-rao-a/go-outline/pull/10.
* `interface` to follow `struct`'s regex approach
* maybe the SymbolKind for type should be TypeParameter

^ outline to include constant & interface

---

src/goDebugConfiguration.ts
src/goFormat.ts
src/goImport.ts
src/goLanguageServer.ts
src/goMain.ts
src/goModules.ts
src/goPackages.ts
src/telemetry.ts
src/util.ts

This change moves all of the telemetry-related code into a separate file, in order centralize it and make it clear what telemetry events the extension sends.

Refactor telemetry handling

---

package.json

This suppresses the lint warning.
There is already the "languages" field.
Context: See github.com/microsoft/vscode/issues/9037

remove obsolete enableBreakpointsFor

---

src/goGenerateTests.ts

The receiver type for a method is now considered. So, if there are >= 1 method names in the same file, then clicking "generate unit tests for function" creates test functions only for the selected method.
funcName like "(*Point).Move" will results in "gotests -w -only ^PointMove$ calls.

Considering receiverType on function test creation issue-2282

---

test/integration/extension.test.ts

Changes in this PR
* Refactor test file to use async/await
* Editors need not be closed after test case
* Add 10 sec timeout for all tests

Refactor test file to use async/await

---

.vscodeignore
build/Dockerfile
build/all.bash

It's not obvious how to run the vscode extension tests - there are many tools and environments involved to run tests reliably in addition to the node dependencies. This PR adds a script that runs the tests in a docker container.

Add a script to enable running tests locally

---

README.md
package.json

The actual code to support the gometalinter was removed
https://github.com/microsoft/vscode-go/pull/2726
This PR removes it from the go.lintTool options so it
no longer appears in the suggested alternative lint tool list
in Go extension setting.

Remove references to gometalinter that's deprecated

---

src/goGenerateTests.ts

https://github.com/microsoft/vscode-go/issues/2822

Fixes Issue #2822

---

src/goInstallTools.ts
src/goPath.ts

1)
If `go.toolsGopath` setting is set, `goInstallTools.installTools` was already setting GOBIN env to ''. With no  `go.toolsGopath` set but GOBIN defined the tools are installed in GOBIN path already. The log message had to be corrected (Installing x tools at ...).
2)
GOBIN was added to the list of places where the extension looks for the tools

Fixes #2122 tools are also found at GOBIN path

---

package-lock.json
package.json

Reverts microsoft/vscode-go#2988
gopls does not depend on the latest language client features. So, let's revert it.
Fixes #3019

Revert "Update to latest vscode-languageclient"

---

src/goLanguageServer.ts

The caller and getLanguageServerToolPath already detected the missing
binary and offered to install the missing tool. So, simply returning
immediately is ok, and prevents the warning messages such as not
handling promise on time, or accessing non-existing property of
tool.name in shouldUpdateLanguageServer.

stop registerLanguageFeatures cleanly when the binary is not installed

---

src/goInstallTools.ts

Skip them from the Install/Update Tools command.
Tools listed in go.alternateTools are supposed to be maintained
by the users.
Fixes #3024

installAllTools: skip tools specified in go.alternateTools

---

src/telemetry.ts

Change-Id: I7157be16784884cb2b6f5ad1a4f82846cba642c6

telemetry.ts: send telemetry only if aiKey is not empty

---

.github/ISSUE_TEMPLATE/bug_report.md

It's a tiny thing, I know, but I couldn't help noticing it. lol

bug_report.md: Fix "architecture" typo

---

src/goInstallTools.ts

Include the link to release note/package overview in the update prompt, and update gopls default version

---

src/debugAdapter/goDebug.ts

This is to fix https://github.com/microsoft/vscode-go/issues/2010. When we are remote debugging cross-compiled binary on Windows, we are not respecting the separator that users use in `remotePath` field.

Fix remote path bug (#2010)

---

src/goLanguageServer.ts

Middleware checks both `editor.parameterHints.enabled` and
`[go].editor.parameterHints.enabled`. The language specific
config takes precedence as long as it is defined.
vscode.workspace.getConfiguration behaves differently when
querying the language-specific configuration section ('[go]')
so I couldn't query [go].editor.parameterHints directly using
getConfiguration.
Tested manually. (sorry)
Fixes #3075

goLanguageServer: set completion follow up command from middleware

---

src/goLint.ts

What Problem
===============
In a project with `.golancci.yml` containing `output: format: checkstyle` (many formats other than checkstyle probably cause the same bug.) vscode will fail to parse warning output from golangci-lint with no discernible error message other than the usual `No problems have been detected in the workspace so far.` in the problems view.  Output in the `Output view > Go tab` shows only the normal `Finished running tool: /home/user/go/bin/golangci-lint run  --print-issued-lines=false`
Solution
--------------
Let's be explicit about a format that we do understand. I chose `colored-line-number` because that's golangci-lint's default according to `golangci-lint run --help`.
Testing
-------------
I approximated tested by setting `"go.lintFlags": …

golangci-lint  --out-format=colored-line-number

---

.travis.yml
build/Dockerfile

Travis Node version seemed to be too old. Update to 8.
Also some minor cleanups 
- update gopkgs tool import path
- update Dockerfile to use go1.14
Fixes microsoft/vscode-go#3073

Fixes linux test in travis

---

src/goDebugConfiguration.ts

When using the debugger in remote attach mode, users have to use `cwd` instead of `program`. This can be confusing so we should show a warning message.

Show warning if 'program' attribute is used in 'remote'

---

src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Bug 1: when generating the default debug configuration
because there is no user-configured one, the extension
dropped noDebug field and caused the program to run with
debugging enabled. Fix it (goDebugConfiguration.ts)
Bug 2: when debug adapter receives noDebug request, it
runs the program with `go run` instead of invoking the
program through dlv. The `go run` will not work in modules
mode if the command runs outside the main module. Set
cwd accordingly.
Fixes microsoft/vscode-go#3121
TESTED=manually with the example attached in #3121

debug: fix 'run without debugging'

---

src/goMain.ts
src/stateUtils.ts

Signed-off-by: Alexandre Vilain <alexandre.vilain@me.com>
Fixes #3118

Keep the last used cover profile path

---

package.json
src/goMain.ts

This command prints the list of configured tools and paths to the tools.
I hope this is useful when debugging the cases where multiple versions
of a tool exist in different directories.
Change-Id: I925422e262978300cbccc97b53d547e4b2f4b146
GitHub-Last-Rev: 4184fd3bb52a51286c3f9950d4710c359a754a03
GitHub-Pull-Request: golang/vscode-go#14
Reviewed-on: https://go-review.googlesource.com/c/vscode-go/+/224098
Reviewed-by: Rebecca Stambler <rstambler@golang.org>

goMain: go.locate.tools command

---

src/debugAdapter/goDebug.ts
src/goDebugConfiguration.ts

Fixing #1229 
Implemented intial proposal by @ramya-rao-a 
When the `program` attribute points to a file (${file} or absolute path), the filepath is now passed to the delve debug command. Thus debugging also works if multiple main files exist in the package. Launching debug from active editor file with no main function (Program = ${file}) will result in following error "Can not debug non-main package". 
Program ${fileDirname} configuration works as before. 
Updated the default value for program attribute in goDebugConfiguration.ts file to be {$file} instead of ${fileDirname}
Documentation [https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code] (url) should be updated e.g. first launch.json example. Since I'm not a native English speaker so not the best person to …

Considering if launch.json's program attribute resolves to a file in debug mode

---

test/integration/extension.test.ts

If the env var GOPATH is not set when the test runs,
now it runs `go env GOPATH` to retrieve the default value
the underlying go commands will use. I wished I could make
this command run asynchronously, but I am not familiar with
the test framework and failed to make it working with
async functions. So, like many other file operations used in
the test setup phase, I am using execFileSync.
Update  golang/vscode-go#6
Change-Id: Id075827ab8ebd955f7a86460aaa7ea4e0e7cd183
GitHub-Last-Rev: 62221580ddaae0062ec79a3ab3efc6258c912117
GitHub-Pull-Request: golang/vscode-go#8
Reviewed-on: https://go-review.googlesource.com/c/vscode-go/+/223177
Reviewed-by: Andrew Bonventre <andybons@golang.org>

test/integration: use default GOPATH when the env var is not set

---

test/integration/extension.test.ts

The error message when there are no Go files to build is changed
in go1.15. That broke this test that includes the diagnostics
message string checking. Adds the message from go1.15 in the
match set.
Fixes microsoft/vscode-go#3130

test/integration: fix Build Tags checking test

---

src/goInstallTools.ts
src/goLanguageServer.ts
src/goTools.ts

PR in Go Nightly: https://github.com/golang/vscode-go/pull/2
I improved the error messages for the `go-langserver` alternate tools setting, but I figured that it might be too much effort to add buttons to make automatic changes for users. I would imagine that most people have already made the switch, and if not, it's quite a small amount of manual work to justify the extra code for different buttons. Once a user changes the setting and reloads their editor, they will be prompted to install `gopls` anyway.
@ramya-rao-a: If you disagree, I'd be happy to add the buttons anyway. If I do that, could you point me to an API reference for how the buttons would work? I got as far as adding items to `vscode.window.showErrorMessage`, but I couldn't figure out how to connect them to functions when …

Remove support for github.com/sourcegraph/go-langserver

---

test/integration/extension.test.ts

Import sources within a group must be alphabetized.
Probably we broke it accidentally while merging two commits back to back.

fix lint error

---

src/debugAdapter/goDebug.ts

The DAP spec allows us to differentiate between stopping on entry and on a breakpoint. 
This is what the UI looked like before:
This is after this change.

Use 'entry' as stopped event reason when stopping on entry

---

src/debugAdapter/goDebug.ts

i have read the issue https://github.com/microsoft/vscode-go/issues/3096 about adding 'go run .' support and i think the commit https://github.com/microsoft/vscode-go/commit/78518d7e9736670d75fe2cd648c7c3eb23413157 has some stuff to work on @ramya-rao-a :
1. the owner of https://github.com/microsoft/vscode-go/issues/3096 just want to solve the problem which can not run a go file without debugging, i think there is no need to pass '.' to `go run` to solve this problem, pass current dir to `cwd` is fine.
2. if pass the '.' to `go run`, users will not check the process, because the executable file will by named as the directory name by go compiler, it's not consistent.

replace . by current file when running without debugging

---

src/debugAdapter/goDebug.ts

The [overview](https://microsoft.github.io/debug-adapter-protocol/overview) says, “Thread events are optional, but a debug adapter can send them to force the development tool to update the threads UI dynamically even when not in a stopped state. If a debug adapter decides not to emit Thread events, the thread UI in the development tool will only update if a stopped event is received.”
Delve does not support events and cannot respond to ListGoroutines requests in running state. Therefore, there is no need for the thread event support here.

debugAdapter: Remove redundant support for thread events

---

src/goDebugConfiguration.ts

When "Start Debugging" or "Run without Debugging" runs without
an explicit launch configuration (launch.json), we need to use
the directory of the file as the program. That is consistent
with the default GoDebugConfigurationProvider provides as the
default DebugConfigurations. (${fileDirname}).
Update microsoft/vscode-go#1229 and microsoft/vscode-go#3096

debug: use fileDirname for the default launch configuration

---

src/goInstallTools.ts

Users can specify the go command to use by setting GOROOT env var,
`go.goroot` vscode setting, or PATH env var. getBinPath('go') is
used to choose the right version of 'go' whenever the extension
tries to invoke the go commands. However, this does not affect
other tools that invoke the go command underneath.
For example, delve, gopls, and many tools simply pick a version of
go from PATH. If the GOROOT env var and the version of go found in
the PATH don't match, this can lead to errors.
This CL places the go runtime base bin path as the first element of
the PATH env var. That ensures any tools invoked by the extension
to pick the same version of go, as long as they stick with the usual
PATH-based executable search.
Note this process.env mutation does not affect the environment variable …

Place the go runtime base path to the front of PATH

---

src/goLanguageServer.ts

We should only have fallbacks for the features that we support opting out of.
Also, remove a few unused imports.
/cc @hyangah

src/goLanguageServer.ts: remove fallbacks for features that cannot be opted-out of

---

README.md
docs/Debugging-Go-code-using-VS-Code.md

delve will hang on the WSL 1 kernel due to trace system call issues.    Just adding a note to that effect.  Would be nice to put in the Wiki under troubleshooting as well.  @ramya-rao-a

Add note about needing WSL 2 on Windows 10

---

src/goInstallTools.ts
src/goLanguageServer.ts
src/goTools.ts

acceptGoplsPrerelease is a const set to false.
We are currently discussing what's the best way to expose this knob to users. 
Meanwhile, developers can flip the var to test whether Gopls picks up the newest version including prerelease.

Logic for gopls updater to accept a pre-release version

---

src/debugAdapter/goDebug.ts

This is similar to another scenario: https://github.com/microsoft/vscode-go/pull/1179
When using the remote debug feature, the paths to remote go module cache might not match the paths to local go module cache.
The idea here is to check if the remote path includes the go module cache sub string, for example: 
`/go/pkg/mod/github.com/account/package`
In this case, it would be a match for the go module cache substring: 
`/pkg/mod/`
And in this case, the path would be replaced by: 
`/Users/someuser/go/pkg/mod/github.com/account/package`
Considering a local gopath like this: 
`$GOPATH="/Users/someuser/go"`.
By doing that, vscode-go can find all source files during debug, including cached modules.
I've made the minimal required changes to make it work for the scenario that I was facing, but …

Map remote go module cache to local module cache

---

src/goInstallTools.ts
src/goLanguageServer.ts

Also, update getMissingTools to check the tool's existence
by simply checking whether the resolved tool path is absolute.
getBinPath already ran the existence check before returning
the absolute path for the tool.
Fixes microsoft/vscode-go#3194

src/goLanguageServer: fix missing gopls detection logic

---

src/goLanguageServer.ts

When the proxy contacted for the released gopls version list does not
respond following the Go module proxy protocol but return unexpected
contents (e.g. login page) semver parsing will fail, trigger an exception,
and cause the language server client not to start.
Fixes #3204

Handle unexpected proxy query results gracefully

---

src/debugAdapter/goDebug.ts

Clarify the error message that is printed to the user when delve returns "bad access".
Updates https://github.com/microsoft/vscode-go/issues/1903.

Debug: Improve 'bad access' error message

---

.travis.yml
.vscode/launch.json
test/gopls/extension.test.ts
test/gopls/index.ts
test/gopls/testfixtures/src/workspace/.gitignore
test/runTest.ts

This CL includes only HoverProvider tests, that use the same scenario
as the hover provider tests with godoc and gogetdoc in
integration/extension.test.ts.
Gopls test setup is complicated because gopls currently does not
work in a single-file mode nor support mono repos with multiple
modules. VS Code in test environment does not support dynamic
registration of workspace folders during testing.  So, the
workspace folder needs to be specified before the extension
host launches (by vscode-test.runTests or launch.json extensionHost
type tasks).
As a workaround, I use an empty directory and start the extension
host with the empty directory for a testing. Then, let the test
populate the directory with necessary files. This is not ideal;
file copy is slow and the use of the single workspace …

test/gopls: initial test setup for gopls and hover tests

---

test/gopls/extension.test.ts

The lint rule was changed since PR microsoft/vscode-go#3157
so the newly added code broke the lint test.
Change-Id: Ic58dfa62e19cb61600b45fe10b43811eb00bc28d
Reviewed-on: https://go-review.googlesource.com/c/vscode-go/+/230297
Reviewed-by: Rebecca Stambler <rstambler@golang.org>

test/gopls: fix the lint error

---

package.json

Now that it is no longer supported, don't let users configure it.

Remove format setting from package.json

---

src/goLanguageServer.ts

This got lost in https://github.com/microsoft/vscode-go/pull/3186.
/cc @hyangah 
Change-Id: I9bb54cdc296315aa15cbce5b078f8c0a36bf5d05

src: fix pre-release logic in the nightly

---

README.md
docs/Go-tools-that-the-Go-extension-depends-on.md

Update microsoft/vscode-go#3233

docs: add link to the Go installation guide

---

README.md

The `#we-are-moving!` links should be `#we-are-moving`, but I moved around the emojis and made a few other cosmetics updates so now they are `#we-are-moving---`. Happy to change anything back, I just liked how the emojis looked inline and wanted to make the announcement a little more visible. You can see how it looks here: https://github.com/stamblerre/vscode-go/tree/readme#go-for-visual-studio-code.
/cc @hyangah

README: fix broken links, a few cosmetic updates
