microsoft/vscode-go

package.json
=> Update the devDepencencies and add typescript 

src/goOutline.ts
=> Adjust symbol position

src/debugAdapter/goDebug.ts
Redirect stdout/err output of Delve to debug console
Fixes #15
=> debugAdapter: Redirect stdout/err of Delve to console

README.md, src/goPath.ts
Fixes #19 and #45.
//cc @mishak87 @ulrichSchreiner
=> Improvements to GOPATH and PATH search for Go tools

src/goMain.ts, src/goOutline.ts
=> Correct typo in class name.

src/goInstallTools.ts
Fix for https://github.com/Microsoft/vscode-go/issues/63
=> Fix for multi-path GOPATH when installing analysis tools.

src/goCheck.ts
=> fixes misleading error message in goCheck

src/goFormat.ts
=> fix misleading error message in goFormat

package.json, src/goFormat.ts, typings/diff-match-patch.d.ts
Use diff-match-patch to apply gofmt as a series of edits.
=> Gofmt patch

src/goFormat.ts
https://github.com/Microsoft/vscode/issues/761
=> Fix regression caused by vscode bug

src/goDeclaration.ts, src/goMain.ts, src/goOutline.ts, src/goSignature.ts, test/go.test.ts
=> Add SignatureHelp support

README.md
Hi guys,
It does not work well when Uppercase.
Lowercase is best.
=> Fix Tools link on README

src/goTest.ts
=> Recognize Example* as a test function.

package.json
Normalize the descriptions for the test commands.
=> Clean up test command descriptions

src/goMain.ts
Fixes #322.
Works around https://github.com/Microsoft/vscode/issues/6373.
=> Fix error reporting to show all errors

package.json
=> Add context menu item for extract method command #275

src/goCheck.ts, src/goCover.ts, src/goInstallTools.ts, src/goPath.ts, src/goTest.ts
=> Better error message when go is not found

README.md
The example to turn off the `formatOnSave` shouldn't be a string value but a boolean.
=> Boolean in JSON shouldn't be quoted as a string.

src/goMain.ts
Doing the same as the PR #406 which keeps failing the travis builds for some reason
=> Remove deprecated language config settings

src/goFormat.ts
=> Only add -d once

package.json, src/goGenerateTests.ts, src/goMain.ts
=> Combine Open test file and Open implemention commands

src/goSuggest.ts
Spec for Package Name: https://golang.org/ref/spec#PackageName
=> Fixes #796 Do not suggest invalid pkg name

src/goMain.ts
`updateGoPathGoRootFromConfig` reads GOPATH from the below, the latter ones overrides the former
- env variable GOPATH
- the new default GOPATH supported in Go 1.8 if env variable GOPATH is not present
- `go.gopath` setting in VS Code
- `go.inferGopath` setting in VS Code
This should be respected by the language server as well.
Therefore, start the language server only after the extension resolves the GOPATH
=> Lang server should use same GOPATH as extension

src/goSuggest.ts
Fixes #572 in "package" and single line "import" statements.
Doesnt fix the issue in case of multi line import statements
=> Dont autocomplete pkg in import and pkg statements

package.json, src/debugAdapter/goDebug.ts, src/goPath.ts
See https://github.com/Microsoft/vscode-go/issues/829#issuecomment-283492838
=> Support envFile in launch.json

package.json, src/goMain.ts, src/goTest.ts
=> Add command to run tests from all directories in workspace

src/goSuggest.ts
=> Use length based iterator in suggest for loop

snippets/go.json
Type `tdt` + tab:
func Test(t *testing.T) {
testCases := []struct {
desc	string
}{
{
desc: "",
},
}
for _, tC := range testCases {
t.Run(tC.desc, func(t *testing.T) {
})
}
}
=> Add snippet for table tests

src/goRunTestCodelens.ts, src/goTest.ts, src/util.ts
#971 was merged before I pushed the changes, so here is the new PR :)
=> changes suggested on #971

README.md
Fixed markdown link to an anchor in Readme.
=> Fixed: Anchor to tools section

src/goTest.ts
=> Fixed test file path expanding in output

src/goRunTestCodelens.ts
This PR fixes #1057 by passing current GOPATH to Delve
=> Pass current GOPATH to Delve. Fix for 1057

src/goCheck.ts
The PR refactors the work done around build on save feature in #1023 to fix the below issues
- The issue found in #846 is back with the work done in #1023 
- The `-i` flag which results in faster builds doesn't get used when building workspace
- The vendor packages get built as well when building workspace See #1060
=> Refactor build workspace on save feature

src/goCover.ts
=> Add check for files outside $GOPATH

src/goPackages.ts, src/goTest.ts
=> Fix the non vendor packages output handling

src/goPackages.ts
=> Ensure only single gopkgs running

src/goInstallTools.ts, src/goMain.ts
Fix the gopkgs install source path
=> Fix gopkgs tools

src/goSuggest.ts, src/util.ts
This should address issue #1260
=> Show package name suggestion "name_test" & "name" for _test.go files

src/goMain.ts, src/goPackages.ts, src/goSuggest.ts, src/util.ts
Enforce internal package rules on autocompletion
Fixes for #1256
=> Add internal package rules

src/goCheck.ts
Fixes #1228 
Had to close/reopen to retrigger build due to [job error](https://travis-ci.org/Microsoft/vscode-go/builds/284677070).
=> Filter duplicate compilation errors

src/goBuild.ts, src/goDeclaration.ts, src/goImplementations.ts, src/goInstall.ts, src/goReferences.ts, src/goRename.ts, test/fixtures/buildTags/hello.go, test/go.test.ts
=> Support multiple buildtags

src/goVet.ts
=> Update go vet for go 1.10 recommendations

package.json, src/goFormat.ts, src/goInstallTools.ts
=> Add support for go.formatTool: "goformat" #1656

README.md
Road testing revive as a part of #1698 and found some small corrections required.
=> doc(README) Fix the revive flags examples.

src/debugAdapter/goDebug.ts
=> Add missing v1 call for evaluateRequest

src/debugAdapter/goDebug.ts
=> Conditional breakpoint support

src/testUtils.ts
I think it just nice to have the x icon, attract more on user attention
Before
After
=> Add x icon to 'Cancel Running Tests

src/goStatus.ts
=> fix: statusbar Analysis Tools Missing text

src/goBrowsePackage.ts, src/goImport.ts, src/goMain.ts, src/goModules.ts, src/goPackages.ts, src/goSuggest.ts, test/go.test.ts
Add module support. All the module dependencies handled by `gopkgs`.
=> Add module support via gopkgs

src/goMain.ts
"few" means "a small number", "a few" means "some".
"recompile", without a hyphen, is a word.
=> Fix grammar in message

.travis.yml
=> Fix golint path

src/goInstallTools.ts
=> Installation of godoc fails due to missing key/value in allTools

CONTRIBUTING.md, src/debugAdapter/Readme.md
=> Fix typos in documentation

src/avlTree.ts, src/goImplementations.ts, src/goLiveErrors.ts, src/util.ts
Found some typos while browsing the code and then decided to run a spellcheck on all of them ;)
=> Fix some typos

.travis.yml
The `if statement` for the Go 1.8 version has a typo in the `else` condition. Fixed.
=> Fix go get command in the pipeline.

README.md, package.json, src/goInstallTools.ts, src/goMain.ts
Now that there is considerable progress in the Sourcegraph language server for Windows, its time we integrate the same in Windows.
=> Language Server in Windows

test/unit/utils.test.ts
Added more util tests. You can check the new util tests works [here](https://travis-ci.org/wachino/vscode-go/jobs/447098019#L896).
Tip: The pipeline is not working since some commits ago in the [vscode-go master branch](https://github.com/Microsoft/vscode-go), for that reason you can see the pipeline also is not working in this PR
=> Add util tests

src/testUtils.ts
Fixes #2071.
Signed-off-by: Charles Kenney <charlesc.kenney@gmail.com>
=> Fix test name regex

src/goTypeDefinition.ts
Additional check to avoid false promt.
=> TypeDefinition: check for builtin type before promt for update

src/goDeclaration.ts, src/goInstallTools.ts
=> godef-gomod to godef

.vscode/tasks.json, src/debugAdapter/goDebug.ts, src/goBrowsePackage.ts, src/goCheck.ts, src/goCodeAction.ts, src/goCover.ts, src/goDebugConfiguration.ts, src/goDeclaration.ts, src/goExtraInfo.ts, src/goImplementations.ts, src/goLint.ts, src/goLiveErrors.ts, src/goMain.ts, src/goModifytags.ts, src/goModules.ts, src/goPackages.ts, src/goPath.ts, src/goReferencesCodelens.ts, src/goRunTestCodelens.ts, src/goSignature.ts, src/goSuggest.ts, src/testUtils.ts, src/util.ts, test/go.test.ts, tsconfig.json
=> Comply with --strict compile flag subset

.travis.yml
- test 1.12 in CI
- remove 1.9 from CI
=> test go 1.12 in CI

snippets/go.json
See https://golang.org/pkg/sort/
Example output: $1: ByName, $2: Badge, $3: a[i].Name < a[j].Name
type ByName []Badge
func (a ByName) Len() int           { return len(a) }
func (a ByName) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a ByName) Less(i, j int) bool { return a[i].Name < a[j].Name }
=> Add snippet for sort.Sort implementation

package.json
=> Set editor.tabSize to 8 for consistency with gofmt

README.md
I couldn't find this in the README, the VS Plugin Marketplace, or anywhere besides this file.
=> Update README.md with link to Code Snippets

src/testUtils.ts
=> go.testEnvVars should override go.testEnvFile

src/debugAdapter/goDebug.ts
This is related to https://github.com/microsoft/vscode-go/issues/2690. When we remote attach a program and set a breakpoint, if we detach and reattach, we cannot clear the breakpoints because we are not retrieving the breakpoint ID.
=> Fix a bug where clearing breakpoints failed

src/util.ts, tslint.json
=> tslint: add one-variable-per-declaration

src/avlTree.ts, src/debugAdapter/goDebug.ts, src/goBrowsePackage.ts, src/goBuild.ts, src/goCover.ts, src/goDeclaration.ts, src/goExtraInfo.ts, src/goImplementations.ts, src/goLint.ts, src/goOutline.ts, src/goPackages.ts, src/goPath.ts, src/goReferences.ts, src/goSuggest.ts, src/goTypeDefinition.ts, src/goVet.ts, src/testUtils.ts, src/util.ts, tslint.json
Part of fixing #2333
I've also removed CRs when I've encountered them on lines which need braces.
=> tslint: add curly

src/goCheck.ts, src/goCover.ts, src/goDeclaration.ts, src/goLanguageServer.ts, src/goTest.ts, src/util.ts, test/integration/extension.test.ts, tslint.json
=> tslint: enable object literal shorthand rule

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Según la lista de verificación, con este PR llegamos a completar punto "Pull resquest remplate"
=> improve open source guides

src/goModifytags.ts
=> use tags and options as default input value

src/goInstallTools.ts
Fixes https://github.com/microsoft/vscode-go/issues/2936
=> correctly set GO111MODULE when installing tools

package-lock.json, package.json
The next version of the vscode-languageclient has been released.
=> Update to latest vscode-languageclient

package.json
MIT license as noted in the LICENSE file
=> specify license info in package.json

package.json
@stamblerre Would you like any other tweaks here?
=> Update description for useLanguageServer setting

snippets/go.json
=> Change index to i in for loop snippet

src/goSymbol.ts
I'm not sure if this will fix the problem in https://github.com/microsoft/vscode-go/issues/3066, but it seems like it might fix the issue in the error message.
=> goSymbol.ts: convert forEach to for-of loop

README.md
=> update README.md mostly where gopls is mentioned

.travis.yml
=> travis-ci: prepare for 1.14 release

src/debugAdapter/goDebug.ts
Fixes a small regression as of #2904 on console logs
=> Restore delve detach error message

package.json
according to https://github.com/microsoft/vscode/issues/90250, we need to escape closing brace.
=> fix #3154 missing brace in placehold

docs/All-Settings-&-Commands-in-Visual-Studio-Code-Go-extension.md, docs/Features-for-Go-in-VS-Code.md, docs/Go-modules-support-in-Visual-Studio-Code.md, docs/Go-with-VS-Code-FAQ-and-Troubleshooting.md
Update microsoft/vscode-go#3148
=> docs: update gopls related documentation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Didn't realize that the config overrides the bug report.md file. Add a redirect to the new repository.
=> add bug report redirect, remove bug_report.md
